import { CONFIG } from './config.js';

let supabase=null,ctx=null,person=null;
const app=document.querySelector('#access-app');
const esc=(v='')=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const token=new URLSearchParams(location.search).get('token')||'';

async function db(){if(supabase)return supabase;const mod=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.117.2/+esm');supabase=mod.createClient(CONFIG.supabaseUrl,CONFIG.supabasePublishableKey,{auth:{persistSession:false,autoRefreshToken:false}});return supabase}
async function rpc(name,args){const c=await db(),{data,error}=await c.rpc(name,args);if(error)throw error;return data}
function baseCard(body){return `<main class="access-public-shell"><section class="access-public-card">${body}</section><p class="access-footer">CRJ Cariacica · Lista de Presença e Contato</p></main>`}
function top(){return `<div class="access-brand"><div class="access-mark">CRJ</div><div><b>CRJ Cariacica</b><small>Presença no uso livre</small></div></div>`}
function stateMessage(title,text,type='info'){return baseCard(`${top()}<div class="access-message ${type}"><h2>${esc(title)}</h2><p>${esc(text)}</p></div>`)}
function startHtml(){return baseCard(`${top()}<div class="access-hero"><span class="access-kicker">${esc(ctx.shift_label||'')}</span><h1>Chegou no CRJ? Bora marcar sua presença ✌️</h1><p>É rapidinho. Isso ajuda a equipe a organizar as salas e garantir sua prioridade de uso.</p></div><form id="identify-form" class="access-stack"><div class="access-choice-row"><label class="access-choice"><input type="radio" name="method" value="cpf" checked><span>Tenho meu CPF</span></label><label class="access-choice"><input type="radio" name="method" value="name"><span>Não lembro o CPF</span></label></div><div class="field"><label data-id-label>CPF</label><input class="input" name="identifier" autocomplete="off" required placeholder="Digite seu CPF"></div><div class="field"><label>Data de nascimento</label><input class="input" type="date" name="birth_date" required></div><button class="btn primary access-big" type="submit">Me encontrar</button><p class="access-help">Não achou seu cadastro? Chama o <b>Controlador(a) de Acessos na recepção</b>. É rapidinho e você não perde sua vez.</p></form>`)}
function roomsHtml(){return baseCard(`${top()}<div class="access-hero compact"><span class="access-kicker">${esc(ctx.shift_label||'')}</span><h1>Aí sim, ${esc(person.display_name)}! 👋</h1><p>Agora marca onde você vai ficar. Isso ajuda a organizar a prioridade das salas.</p></div><form id="room-form" class="access-stack"><div class="access-room-grid">${(ctx.rooms||[]).map(r=>`<label class="access-room"><input type="checkbox" name="room_ids" value="${r.id}"><span><b>${esc(r.name)}</b><small>${esc(r.description||'Espaço do CRJ')}${r.capacity!=null?' · capacidade '+r.capacity:''}</small></span></label>`).join('')}</div>${!(ctx.rooms||[]).length?'<div class="access-message warn"><p>Nenhuma sala está liberada para uso livre agora. Chama a recepção.</p></div>':''}<button class="btn primary access-big" type="submit" ${(ctx.rooms||[]).length?'':'disabled'}>${person.already_current_shift?'Atualizar minha sala':'Confirmar minha presença'}</button><button class="btn ghost access-big" type="button" data-back>Voltar</button></form>`)}
function successHtml(name){return baseCard(`${top()}<div class="access-success"><div class="access-check">✓</div><h1>Presença marcada!</h1><p>Valeu, ${esc(name)}. Agora é só aproveitar o CRJ 🙌</p><p class="access-help">Se você continuar no CRJ no próximo turno, passa aqui de novo e confirma sua presença.</p><button class="btn primary access-big" data-next>Próximo jovem</button></div>`)}

async function loadContext(){if(!token){app.innerHTML=stateMessage('Link inválido','Peça ao Controlador de Acessos o link da lista de hoje.','danger');return false}try{ctx=await rpc('access_public_context',{p_token:token});if(!ctx?.ok){app.innerHTML=stateMessage('Link inválido',ctx?.message||'Esta lista não está disponível.','danger');return false}if(!ctx.open){app.innerHTML=stateMessage('Lista encerrada','A lista de hoje não está aberta. Fale com a recepção.','warn');return false}if(!ctx.shift){app.innerHTML=stateMessage('Fora do horário de registro','A presença pelo link funciona nos turnos 07h–12h e 12h–18h. Fale com a recepção se precisar de ajuda.','warn');return false}return true}catch(err){app.innerHTML=stateMessage('Não foi possível abrir a lista',err.message||'Tente novamente na recepção.','danger');return false}}
function bindStart(){const form=document.querySelector('#identify-form'),label=document.querySelector('[data-id-label]'),input=form.querySelector('[name="identifier"]');form.querySelectorAll('[name="method"]').forEach(r=>r.addEventListener('change',()=>{const name=form.querySelector('[name="method"]:checked').value==='name';label.textContent=name?'Nome completo':'CPF';input.placeholder=name?'Digite seu nome completo':'Digite seu CPF';input.value='';input.focus()}));form.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(form),btn=form.querySelector('button[type="submit"]'),old=btn.textContent;btn.disabled=true;btn.textContent='Procurando...';try{const out=await rpc('access_public_identify',{p_token:token,p_identifier:fd.get('identifier'),p_birth_date:fd.get('birth_date')});if(out?.found){person=out;app.innerHTML=roomsHtml();bindRooms();return}const messages={not_found:'Não achamos seu cadastro com esses dados.',ambiguous:'Encontramos mais de um cadastro parecido e precisamos confirmar com você.',closed:'A lista foi encerrada.',outside_shift:'Estamos fora do turno de registro.',missing:'Confira os dados informados.'};const msg=messages[out?.reason]||'Não conseguimos localizar seu cadastro.';const warn=document.createElement('div');warn.className='access-message warn';warn.innerHTML=`<b>${esc(msg)}</b><p>Chama o Controlador(a) de Acessos na recepção. Ele resolve rapidinho.</p>`;form.querySelector('.access-message')?.remove();form.prepend(warn)}catch(err){const warn=document.createElement('div');warn.className='access-message danger';warn.textContent=err.message||'Não foi possível consultar agora.';form.prepend(warn)}finally{btn.disabled=false;btn.textContent=old}})}
function bindRooms(){document.querySelector('[data-back]')?.addEventListener('click',()=>{person=null;app.innerHTML=startHtml();bindStart()});const form=document.querySelector('#room-form');form?.addEventListener('submit',async e=>{e.preventDefault();const rooms=[...form.querySelectorAll('[name="room_ids"]:checked')].map(x=>x.value);if(!rooms.length){const warn=document.createElement('div');warn.className='access-message warn';warn.textContent='Marca pelo menos uma sala/espaço antes de continuar.';form.querySelector('.access-message')?.remove();form.prepend(warn);return}const btn=form.querySelector('button[type="submit"]'),old=btn.textContent;btn.disabled=true;btn.textContent='Marcando...';try{const out=await rpc('access_public_mark_presence',{p_token:token,p_youth_id:person.youth_id,p_room_ids:rooms});app.innerHTML=successHtml(out?.display_name||person.display_name);bindSuccess()}catch(err){const warn=document.createElement('div');warn.className='access-message danger';warn.textContent=err.message||'Não foi possível marcar a presença.';form.prepend(warn);btn.disabled=false;btn.textContent=old}})}
function bindSuccess(){let timer=setTimeout(reset,4500);document.querySelector('[data-next]')?.addEventListener('click',()=>{clearTimeout(timer);reset()})}
async function reset(){person=null;if(await loadContext()){app.innerHTML=startHtml();bindStart()}}
async function boot(){if(await loadContext()){app.innerHTML=startHtml();bindStart()}}
boot();
