import { CONFIG } from './config.js';

const app=document.querySelector('#demand-app');
const token=new URLSearchParams(location.search).get('t')||'';
const ENDPOINT=`${CONFIG.supabaseUrl}/functions/v1/articulation-demand-public`;
const GENDERS=['Mulher cisgênero','Homem cisgênero','Mulher transgênero','Homem transgênero','Travesti','Pessoa não binária','Pessoa agênero','Pessoa de gênero fluido','Outra identidade de gênero','Prefiro não informar'];
const ORIENTATIONS=['Heterossexual','Gay','Lésbica','Bissexual','Pansexual','Assexual','Demissexual','Queer / outra orientação','Em questionamento','Prefiro não informar'];
const RELIGIONS=['Sem religião','Católica','Evangélica / Protestante','Espírita / Kardecista','Umbanda','Candomblé','Outra religião de matriz africana','Tradição religiosa indígena','Judaísmo','Islamismo','Budismo','Hinduísmo','Outra religião oriental','Ateu / Agnóstico','Outra'];
const RACES=['Preta','Branca','Indígena','Parda','Amarela','Prefiro não informar'];
const CATEGORIES=['Cultura / Arte','Esporte / Lazer','Formação / Oficinas','Trabalho / Renda','Educação','Saúde / Bem-estar','Direitos / Documentação','Mobilidade','Convivência / Território','Outra'];
const DAYS=['Segunda','Terça','Quarta','Quinta','Sexta'];
const SHIFTS=['Manhã','Tarde','Noite'];
let boot=null,lastSubmission=null,lastSelected=[];

const esc=(v='')=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const opts=a=>`<option value=""></option>${a.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}`;
const checks=(a,name)=>`<div class="checks">${a.map(x=>`<label class="check"><input type="checkbox" name="${name}" value="${esc(x)}"><span>${esc(x)}</span></label>`).join('')}</div>`;
const fmtTime=v=>String(v||'').slice(0,5)||'horário a confirmar';

async function call(action,payload={}){
  const r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json','apikey':CONFIG.supabasePublishableKey},body:JSON.stringify({action,token,...payload})});
  const ct=r.headers.get('content-type')||'';
  const data=ct.includes('application/json')?await r.json():await r.text();
  if(!r.ok)throw new Error(data?.error||String(data)||'Não foi possível concluir.');
  return data;
}

function workshopCards(rows=[]){if(!rows.length)return '<div class="notice info">Ainda não há oficinas abertas para inscrição por este link.</div>';return `<div class="workshops">${rows.map(w=>`<label class="workshop"><input type="checkbox" name="workshop_ids" value="${w.id}"><span><b>${esc(w.name)}</b><small>${esc(w.days||'Dias a confirmar')} · ${esc(fmtTime(w.start_time))}${w.end_time?' às '+esc(fmtTime(w.end_time)):''}${w.location_other?' · '+esc(w.location_other):''}</small></span></label>`).join('')}</div>`}

function renderForm(data){boot=data;const title=data?.link?.title||'Formulário de Demanda · CRJ Cariacica',intro=data?.link?.intro||'Conta pra gente o que você gostaria que acontecesse no CRJ.';app.className='';app.innerHTML=`
  <form id="demand-form">
    <section class="card"><h2 class="section-title">${esc(title)}</h2><p class="sub">${esc(intro)}</p><div class="notice info"><b>Articulador responsável:</b> Sistema<br><b>Data do levantamento:</b> ${esc(data.today)} <span class="tiny">(definida automaticamente)</span></div><input class="hp" name="website" autocomplete="off" tabindex="-1"></section>

    <section class="card"><h2 class="section-title">Primeiro, quem é você?</h2><p class="sub">Esses dados criam um cadastro inicial provisório no CRJ. O que faltar poderá ser completado depois com a equipe.</p><div class="grid"><div class="field"><label>Nome completo *</label><input name="full_name" required></div><div class="field"><label>Como prefere ser chamado? (nome social)</label><input name="social_name"></div></div><div class="grid"><div class="field"><label>Data de nascimento</label><input type="date" name="birth_date"></div><div class="field"><label>CPF <span class="tiny">(opcional, ajuda a evitar cadastro duplicado)</span></label><input name="cpf" inputmode="numeric"></div></div><div class="grid"><div class="field"><label>Telefone</label><input name="phone" inputmode="tel"></div><div class="field"><label>E-mail</label><input name="email" type="email"></div></div><div class="field"><label>Onde você mora? Rua, nº e referência</label><input name="residence"></div><div class="grid"><div class="field"><label>Bairro</label><input name="neighborhood"></div><div class="field"><label>Município</label><input name="municipality" value="Cariacica"></div></div></section>

    <section class="card"><h2 class="section-title">Sobre você</h2><p class="sub">Essas respostas ajudam o CRJ a entender quem está participando e onde precisa melhorar a atuação.</p><div class="grid"><div class="field"><label>Cor / raça</label><select name="race">${opts(RACES)}</select></div><div class="field"><label>Identidade de gênero</label><select name="gender_identity">${opts(GENDERS)}</select></div></div><div class="grid"><div class="field"><label>Orientação sexual</label><select name="sexual_orientation">${opts(ORIENTATIONS)}</select></div><div class="field"><label>Religião / crença</label><select name="religion" data-religion>${opts(RELIGIONS)}</select></div></div><div class="field hidden" data-religion-other-wrap><label>Qual outra religião / crença?</label><input name="religion_other"></div></section>

    <section class="card"><h2 class="section-title">Agora manda a real.</h2><div class="field"><label>Dentro do território, onde você costuma encontrar seus amigos?</label><textarea name="friend_places"></textarea></div><div class="field"><label>Qual oficina ou atividade você gostaria que tivesse no CRJ? *</label><textarea name="desired_workshop" required></textarea></div><div class="field"><label>Descreva sua principal demanda / ideia</label><textarea name="demand_description"></textarea></div><div class="field"><label>Que tipo de demanda é essa?</label>${checks(CATEGORIES,'demand_categories')}</div><div class="grid"><div class="field"><label>Quais dias são melhores?</label>${checks(DAYS,'preferred_days')}</div><div class="field"><label>Qual turno funciona melhor?</label>${checks(SHIFTS,'availability_shifts')}</div></div><div class="field"><label>O que você acha que falta na sua comunidade?</label><textarea name="community_missing"></textarea></div><div class="field"><label>Quais lugares você gostaria de conhecer?</label><textarea name="places_to_visit"></textarea></div><div class="field"><label>Você tem alguma habilidade ou dom? Conta aí.</label><textarea name="skills"></textarea></div></section>

    <section class="card"><h2 class="section-title">Já tem coisa rolando no CRJ 👀</h2><p class="sub">Se alguma oficina abaixo fizer sentido pra você, marque e a gente já registra sua inscrição. Depois do envio, você recebe uma agenda pessoal com dias e horários.</p>${workshopCards(data.workshops||[])}</section>

    <section class="card"><div class="notice info">Ao enviar, sua resposta entra no levantamento de demandas do CRJ. Se você escolher uma oficina, sua inscrição ficará ligada ao cadastro provisório até a equipe completar os dados que faltarem.</div><div class="actions"><button class="btn primary" type="submit">Enviar minha demanda</button></div></section>
  </form>`;
  const religion=app.querySelector('[data-religion]'),other=app.querySelector('[data-religion-other-wrap]');religion?.addEventListener('change',()=>other?.classList.toggle('hidden',religion.value!=='Outra'));
  app.querySelector('#demand-form').addEventListener('submit',submit);
}

function value(fd,k){return String(fd.get(k)||'').trim()||null}
function values(fd,k){return fd.getAll(k).map(x=>String(x).trim()).filter(Boolean)}
async function submit(e){e.preventDefault();const form=e.currentTarget,btn=form.querySelector('button[type="submit"]');btn.disabled=true;btn.textContent='Enviando…';try{const fd=new FormData(form),selectedIds=values(fd,'workshop_ids');lastSelected=(boot?.workshops||[]).filter(w=>selectedIds.includes(w.id));const payload={website:value(fd,'website'),full_name:value(fd,'full_name'),social_name:value(fd,'social_name'),birth_date:value(fd,'birth_date'),cpf:value(fd,'cpf'),phone:value(fd,'phone'),email:value(fd,'email'),residence:value(fd,'residence'),neighborhood:value(fd,'neighborhood'),municipality:value(fd,'municipality'),race:value(fd,'race'),gender_identity:value(fd,'gender_identity'),sexual_orientation:value(fd,'sexual_orientation'),religion:value(fd,'religion'),religion_other:value(fd,'religion_other'),friend_places:value(fd,'friend_places'),desired_workshop:value(fd,'desired_workshop'),demand_description:value(fd,'demand_description'),demand_categories:values(fd,'demand_categories'),preferred_days:values(fd,'preferred_days'),availability_shifts:values(fd,'availability_shifts'),community_missing:value(fd,'community_missing'),places_to_visit:value(fd,'places_to_visit'),skills:value(fd,'skills'),workshop_ids:selectedIds};const data=await call('submit',{payload});lastSubmission={...data,name:payload.social_name||payload.full_name};renderSuccess(lastSubmission,lastSelected);if(lastSelected.length)await downloadAgenda(lastSubmission,lastSelected,true)}catch(err){btn.disabled=false;btn.textContent='Enviar minha demanda';const old=form.querySelector('[data-submit-error]');old?.remove();const d=document.createElement('div');d.dataset.submitError='1';d.className='notice danger';d.textContent=err.message||String(err);btn.closest('.card')?.prepend(d)}}

function renderSuccess(data,selected){app.className='';app.innerHTML=`<section class="card"><div class="notice success"><b>Fechou! Sua resposta chegou no CRJ.</b><br>O articulador responsável aparece como <b>Sistema</b> e a data do levantamento foi registrada automaticamente.</div><h2 class="section-title">Sua demanda já está mapeada.</h2><p class="sub">Seu cadastro inicial ficou como <b>provisório</b>. A equipe poderá completar o que ainda estiver pendente depois.</p>${selected.length?`<h3>Oficinas em que você se inscreveu</h3><div class="agenda-list">${selected.map(w=>`<div class="agenda-item"><b>${esc(w.name)}</b><span>${esc(w.days||'Dias a confirmar')} · ${esc(fmtTime(w.start_time))}${w.end_time?' às '+esc(fmtTime(w.end_time)):''}</span></div>`).join('')}</div><div class="actions" style="margin-top:18px"><button class="btn primary" data-download-agenda>Baixar minha agenda em PDF</button></div>`:'<div class="notice info">Você não marcou uma oficina existente agora. Sua demanda continua registrada normalmente.</div>'}</section>`;app.querySelector('[data-download-agenda]')?.addEventListener('click',()=>downloadAgenda(data,selected,false))}

async function downloadAgenda(data,workshops,automatic=false){try{const {PDFDocument,StandardFonts,rgb}=await import('https://cdn.jsdelivr.net/npm/pdf-lib@1.17.1/+esm');const pdf=await PDFDocument.create(),regular=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);let page=pdf.addPage([595.28,841.89]),y=790;const left=48,max=499;const clean=v=>String(v||'').replace(/[\u{1F300}-\u{1FAFF}]/gu,'').replace(/[—–]/g,'-').replace(/\s+/g,' ').trim();const wrap=(font,size,text)=>{const words=clean(text).split(' '),lines=[];let line='';for(const word of words){const test=line?line+' '+word:word;if(font.widthOfTextAtSize(test,size)<=max)line=test;else{if(line)lines.push(line);line=word}}if(line)lines.push(line);return lines};const newPage=()=>{page=pdf.addPage([595.28,841.89]);y=790};const draw=(text,size=11,font=regular,gap=16)=>{for(const l of wrap(font,size,text)){if(y<70)newPage();page.drawText(l,{x:left,y,size,font,color:rgb(.08,.18,.16)});y-=gap}};page.drawRectangle({x:0,y:760,width:595.28,height:82,color:rgb(.04,.36,.30)});page.drawText('CRJ CARIACICA',{x:left,y:808,size:13,font:bold,color:rgb(1,1,1)});page.drawText('Sua agenda de oficinas',{x:left,y:779,size:24,font:bold,color:rgb(1,1,1)});y=725;draw(`Salve, ${clean(data.name)||'jovem'}! Bora se organizar? Aqui está o resumão das oficinas que você escolheu.`,13,bold,19);y-=5;draw('Seu cadastro inicial está provisório. Depois a equipe do CRJ completa com você o que ainda estiver faltando.',10,regular,15);y-=16;for(const w of workshops){if(y<175)newPage();page.drawRectangle({x:left,y:y-92,width:max,height:102,color:rgb(.95,.98,.97),borderColor:rgb(.77,.88,.84),borderWidth:1});page.drawText(clean(w.name),{x:left+14,y:y-24,size:15,font:bold,color:rgb(.04,.36,.30)});page.drawText(clean(`${w.days||'Dias a confirmar'} - ${fmtTime(w.start_time)}${w.end_time?' às '+fmtTime(w.end_time):''}`),{x:left+14,y:y-48,size:11,font:regular,color:rgb(.08,.18,.16)});page.drawText(clean(`Local: ${w.location_other||w.location_type||'CRJ Cariacica'}`),{x:left+14,y:y-70,size:10,font:regular,color:rgb(.2,.28,.26)});page.drawText('Chega uns minutinhos antes. Se pintar dúvida, cola com a equipe!',{x:left+14,y:y-88,size:9,font:regular,color:rgb(.25,.32,.30)});y-=122}y-=4;draw('CRJ Cariacica - Rua Che Guevara, 191, Castelo Branco, Cariacica - ES',9,regular,14);draw('Contato: (27) 98171-0035',9,regular,14);const bytes=await pdf.save(),blob=new Blob([bytes],{type:'application/pdf'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='minha-agenda-crj-cariacica.pdf';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),5000)}catch(err){console.error('PDF agenda',err);if(!automatic)alert('Sua inscrição foi salva, mas o PDF não pôde ser gerado agora. Tente novamente pelo botão de download.')}}

async function start(){if(!token){app.className='card';app.innerHTML='<div class="notice danger"><b>Link incompleto.</b><br>Peça à equipe de Articulação um novo link de levantamento de demandas.</div>';return}try{renderForm(await call('bootstrap'))}catch(err){app.className='card';app.innerHTML=`<div class="notice danger"><b>Esse link não está disponível.</b><br>${esc(err.message||err)}</div>`}}
start();
