import { CONFIG } from './config.js';
const app=document.querySelector('#demand-app');
const token=new URLSearchParams(location.search).get('t')||'';
const endpoint=`${CONFIG.supabaseUrl}/functions/v1/articulation-demand-public`;
let canvas,ctx,drawing=false,signed=false;
const selected=form=>[...form.querySelectorAll('input[name="workshop_ids"]:checked')];
const values=(fd,k)=>fd.getAll(k).map(x=>String(x).trim()).filter(Boolean);
const value=(fd,k)=>String(fd.get(k)||'').trim()||null;
function enhance(form){if(form.dataset.formalEnrollment)return;form.dataset.formalEnrollment='1';const first=form.querySelector('input[name="workshop_ids"]');if(!first)return;const section=first.closest('section.card');const box=document.createElement('section');box.className='card hidden';box.dataset.formalBox='1';box.innerHTML='<h2 class="section-title">Concluir inscrição nas oficinas</h2><p class="sub">Se você marcar uma oficina, complete CPF, e-mail, bairro, assinatura e um código de presença. Esse código será usado somente para confirmar presença na lista virtual.</p><div class="field"><label>Assinatura manuscrita *</label><canvas data-sign style="width:100%;height:180px;border:1px solid #cfdad6;border-radius:11px;background:#fff;touch-action:none"></canvas><div class="actions" style="margin-top:8px"><button class="btn secondary" type="button" data-clear>Limpar assinatura</button></div></div><div class="grid"><div class="field"><label>Código de presença *</label><input name="presence_code" minlength="4" maxlength="32" autocomplete="off"></div><div class="field"><label>Confirmar código *</label><input name="presence_code_confirm" minlength="4" maxlength="32" autocomplete="off"></div></div>';section.insertAdjacentElement('afterend',box);canvas=box.querySelector('[data-sign]');const resize=()=>{const r=canvas.getBoundingClientRect(),ratio=Math.max(1,window.devicePixelRatio||1);canvas.width=Math.floor(Math.max(r.width,320)*ratio);canvas.height=Math.floor(180*ratio);ctx=canvas.getContext('2d');ctx.scale(ratio,ratio);ctx.lineWidth=2.2;ctx.lineCap='round';ctx.strokeStyle='#10211d'};resize();const point=e=>{const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}};canvas.onpointerdown=e=>{drawing=true;const p=point(e);ctx.beginPath();ctx.moveTo(p.x,p.y);canvas.setPointerCapture?.(e.pointerId)};canvas.onpointermove=e=>{if(!drawing)return;const p=point(e);ctx.lineTo(p.x,p.y);ctx.stroke();signed=true};canvas.onpointerup=canvas.onpointerleave=()=>drawing=false;box.querySelector('[data-clear]').onclick=()=>{signed=false;ctx.clearRect(0,0,canvas.width,canvas.height)};const sync=()=>{const active=selected(form).length>0;box.classList.toggle('hidden',!active);['cpf','email','neighborhood'].forEach(n=>{const el=form.querySelector(`[name="${n}"]`);if(el)el.required=active})};form.querySelectorAll('input[name="workshop_ids"]').forEach(x=>x.addEventListener('change',sync));sync()}
function buildPayload(form){const fd=new FormData(form),chosen=selected(form);return{website:value(fd,'website'),full_name:value(fd,'full_name'),social_name:value(fd,'social_name'),birth_date:value(fd,'birth_date'),cpf:value(fd,'cpf'),phone:value(fd,'phone'),email:value(fd,'email'),residence:value(fd,'residence'),neighborhood:value(fd,'neighborhood'),municipality:value(fd,'municipality'),race:value(fd,'race'),gender_identity:value(fd,'gender_identity'),sexual_orientation:value(fd,'sexual_orientation'),religion:value(fd,'religion'),religion_other:value(fd,'religion_other'),friend_places:value(fd,'friend_places'),desired_workshop:value(fd,'desired_workshop'),demand_description:value(fd,'demand_description'),demand_categories:values(fd,'demand_categories'),preferred_days:values(fd,'preferred_days'),availability_shifts:values(fd,'availability_shifts'),community_missing:value(fd,'community_missing'),places_to_visit:value(fd,'places_to_visit'),skills:value(fd,'skills'),workshop_ids:chosen.map(x=>x.value),signature_data:chosen.length&&signed?canvas.toDataURL('image/png'):null,checkin_secret:chosen.length?String(fd.get('presence_code')||''):null,checkin_secret_confirm:chosen.length?String(fd.get('presence_code_confirm')||''):null}}
async function submit(e){const form=e.target;if(form.id!=='demand-form'||!form.dataset.formalEnrollment)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();const chosen=selected(form);if(chosen.length){const cpf=String(form.querySelector('[name="cpf"]')?.value||'').replace(/\D/g,'');if(cpf.length!==11)return alert('Para se inscrever na oficina, informe o CPF completo.');if(!form.querySelector('[name="email"]')?.value.trim())return alert('Para se inscrever na oficina, informe o e-mail.');if(!form.querySelector('[name="neighborhood"]')?.value.trim())return alert('Para se inscrever na oficina, informe o bairro.');if(!signed)return alert('Assine no campo de assinatura para concluir a inscrição.');const a=form.querySelector('[name="presence_code"]')?.value||'',b=form.querySelector('[name="presence_code_confirm"]')?.value||'';if(a.length<4||a.length>32)return alert('O código de presença deve ter entre 4 e 32 caracteres.');if(a!==b)return alert('A confirmação do código de presença não confere.')}
const btn=form.querySelector('button[type="submit"]');btn.disabled=true;btn.textContent='Enviando…';try{const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json','apikey':CONFIG.supabasePublishableKey},body:JSON.stringify({action:'submit',token,payload:buildPayload(form)})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data?.error||'Não foi possível concluir.');const names=chosen.map(x=>x.closest('.workshop')?.querySelector('b')?.textContent?.trim()).filter(Boolean);app.innerHTML=`<section class="card"><div class="notice success"><b>Sua demanda foi registrada.</b><br>${data.linked_existing?'Ela foi ligada ao cadastro que você já possuía.':'Foi criado um Formulário Inicial provisório ligado à demanda.'}</div>${names.length?`<h2 class="section-title">Inscrição concluída</h2><p class="sub">Sua assinatura e seu código de presença foram vinculados às oficinas selecionadas. Use esse código quando a lista virtual da aula estiver aberta.</p><div class="agenda-list">${names.map(n=>`<div class="agenda-item"><b>${n}</b></div>`).join('')}</div>`:'<div class="notice info">Nenhuma oficina foi selecionada. A demanda foi salva normalmente.</div>'}</section>`}catch(err){btn.disabled=false;btn.textContent='Enviar minha demanda';let d=form.querySelector('[data-submit-error]');if(!d){d=document.createElement('div');d.dataset.submitError='1';d.className='notice danger';btn.closest('.card')?.prepend(d)}d.textContent=err.message||String(err)}}
document.addEventListener('submit',submit,true);const obs=new MutationObserver(()=>{const form=document.querySelector('#demand-form');if(form)enhance(form)});obs.observe(app||document.documentElement,{childList:true,subtree:true});const f=document.querySelector('#demand-form');if(f)enhance(f);
