import './document_delete.js?v=20261007-1';
import { apiMode, supabaseClient, updateYouth, saveFormSubmission } from './api.js?v=20261004-2';
import { FORMS } from './forms.js';
import { canFillForm } from './permissions.js';
import { CONFIG } from './config.js';

let me=null,rendering=false,timer=null;
const esc=(v='')=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=v=>v?new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v)):'—';
const labels={
  'levantamento-demanda':'Levantamento de Demanda',
  'acao-levantamento-demanda':'Ação de Levantamento de Demanda',
  'plano-mobilizacao':'Plano de Mobilização',
  'acao-articulacao':'Ação da Articulação'
};
const missingLabel=k=>({full_name:'nome completo',birth_date:'data de nascimento',cpf:'CPF',phone:'telefone',neighborhood:'bairro',activity:'atividade',date:'data',facilitator:'facilitador(a)',activity_type:'tipo de atividade',request_number:'número da solicitação',requester:'solicitante',item:'item',loan_date:'data do empréstimo',return_date:'data de devolução',staff_name:'colaborador(a)',reference_educator:'educador(a) de referência',start_date:'data inicial',reference_team:'equipe de referência',class_name:'turma',reference:'referência',desired_workshop:'oficina/atividade desejada',title:'título',objective:'objetivo',target_audience:'público',planned_date:'data prevista',mobilization_goal:'objetivo da mobilização',territories:'territórios',strategies:'estratégias',mobilization_deadline:'prazo'}[k]||String(k||'').replaceAll('_',' '));
function c(){if(apiMode()!=='live')throw new Error('Banco ainda não conectado.');return supabaseClient()}
function isRoute(){return location.hash.split('?')[0]==='#documentos-evidencias'}
function params(){return new URLSearchParams(location.hash.split('?')[1]||'')}
async function ready(){for(let i=0;i<80;i++){if(apiMode()==='live'){try{const cl=supabaseClient(),{data:{user}}=await cl.auth.getUser();if(user){const {data,error}=await cl.from('profiles').select('id,display_name,role,team,active').eq('id',user.id).single();if(error)throw error;me=data;return true}}catch{}}await new Promise(r=>setTimeout(r,120))}return false}
function style(){if(document.querySelector('#doc-drafts-css'))return;const s=document.createElement('style');s.id='doc-drafts-css';s.textContent=`
.dd-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;margin-bottom:14px}.dd-kpis{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin:12px 0}.dd-kpi,.dd-card{background:#fff;border:1px solid #dfe7e4;border-radius:14px;padding:14px}.dd-kpi b{font-size:24px;display:block}.dd-filter{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.dd-filter button{border:1px solid #d8e3df;background:#fff;padding:7px 10px;border-radius:999px;cursor:pointer}.dd-filter button.active{background:#0b5b4c;color:#fff}.dd-row{border:1px solid #e2e9e6;border-radius:12px;padding:13px;margin:9px 0}.dd-row-head{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.dd-meta{font-size:12px;color:#68746f}.dd-draft{margin:8px 0;padding:8px 10px;background:#fff8e8;border:1px solid #ead7a9;border-radius:9px;font-size:12px}.dd-complete{margin:8px 0;padding:7px 9px;background:#edf8f1;border:1px solid #cce5d4;border-radius:9px;font-size:12px}.dd-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:9px}.dd-modal-bg{position:fixed;inset:0;z-index:2147483200;background:rgba(4,17,21,.7);display:grid;place-items:center;padding:10px}.dd-modal{width:min(1050px,98vw);max-height:96vh;overflow:auto;background:#fff;border-radius:16px}.dd-modal header,.dd-modal .body,.dd-modal footer{padding:15px 18px}.dd-modal header{position:sticky;top:0;background:#fff;z-index:2;display:flex;justify-content:space-between;border-bottom:1px solid #e3e9e7}.dd-modal footer{position:sticky;bottom:0;background:#fff;border-top:1px solid #e3e9e7;display:flex;justify-content:flex-end;gap:8px}.dd-section{border:1px solid #e2e9e6;border-radius:12px;padding:12px;margin:10px 0}.dd-section h4{margin:0 0 10px}.dd-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.dd-checks{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px}.dd-check{display:flex;gap:7px;align-items:flex-start;border:1px solid #e4ebe8;border-radius:9px;padding:7px}.dd-source{display:inline-flex;padding:4px 7px;border-radius:999px;background:#eef4f2;font-size:11px}.dd-source.public{background:#eef0ff;color:#433a8c}@media(max-width:760px){.dd-kpis,.dd-grid,.dd-checks{grid-template-columns:1fr}.dd-head,.dd-row-head{flex-direction:column}}
`;document.head.appendChild(s)}
function formDef(slug){return FORMS.find(f=>f.slug===slug)||null}
function titleOf(row){const f=formDef(row.form_slug);return f?`${f.annex} — ${f.title}`:(labels[row.form_slug]||row.form_slug||'Documento')}
function stateHtml(row){const miss=(row.incomplete_fields||[]).map(missingLabel);if(row.record_state==='complete'&&!miss.length)return '<div class="dd-complete"><b>Documento concluído</b> · continua disponível para consulta e exportação.</div>';return `<div class="dd-draft"><b>Rascunho</b>${miss.length?` · dados incompletos: ${esc(miss.join(', '))}`:' · revise os dados antes de concluir.'}</div>`}
async function load(){const cl=c();let q=cl.from('methodology_form_submissions').select('id,form_slug,youth_id,payload,sensitivity,submitted_at,updated_at,created_by,record_state,incomplete_fields,source_type,source_id').order('updated_at',{ascending:false}).limit(400);const r=await q;if(r.error)throw r.error;const rows=r.data||[];const yids=[...new Set(rows.map(x=>x.youth_id).filter(Boolean))];let youth=[];if(yids.length){const y=await cl.from('young_people').select('id,full_name,preferred_name,initial_form_status').in('id',yids);if(y.error)throw y.error;youth=y.data||[]}const ym=new Map(youth.map(x=>[x.id,x]));return rows.map(x=>({...x,_youth:ym.get(x.youth_id)||null}))}
function filterRows(rows){const f=params().get('filter')||'rascunhos';if(f==='todos')return rows;if(f==='concluidos')return rows.filter(x=>x.record_state==='complete');if(f==='anexos')return rows.filter(x=>!!formDef(x.form_slug));if(f==='articulacao')return rows.filter(x=>['levantamento-demanda','acao-levantamento-demanda','plano-mobilizacao','acao-articulacao'].includes(x.form_slug));return rows.filter(x=>x.record_state!=='complete'||(x.incomplete_fields||[]).length)}
function routeFilter(v){location.hash='#documentos-evidencias?filter='+encodeURIComponent(v)}
function sourceEditLink(row){if(['levantamento-demanda','acao-levantamento-demanda','plano-mobilizacao','acao-articulacao'].includes(row.form_slug))return '#articulacao?view='+(row.form_slug==='plano-mobilizacao'?'planos':row.form_slug==='levantamento-demanda'||row.form_slug==='acao-levantamento-demanda'?'demandas':'acoes');if(row.youth_id)return `#jovem/${row.youth_id}`;return '#formularios'}
async function exportDoc(id,format){const cl=c(),{data:{session}}=await cl.auth.getSession();if(!session)throw new Error('Sessão expirada.');const res=await fetch(`${CONFIG.supabaseUrl}/functions/v1/crj-export-document`,{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json',apikey:CONFIG.supabasePublishableKey},body:JSON.stringify({submission_id:id,format})});if(!res.ok){let m='Falha ao gerar documento.';try{m=(await res.json()).error||m}catch{}throw new Error(m)}const blob=await res.blob(),url=URL.createObjectURL(blob),a=document.createElement('a'),cd=res.headers.get('content-disposition')||'';a.href=url;a.download=(cd.match(/filename="([^"]+)"/)||[])[1]||`documento.${format}`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),4000)}
function inputField(field,value){const key=field.key,label=field.label||key,val=value??'',help=field.help?`<small>${esc(field.help)}</small>`:'';if(field.type==='textarea')return `<div class="field"><label>${esc(label)}</label><textarea name="${esc(key)}">${esc(val)}</textarea>${help}</div>`;if(field.type==='select')return `<div class="field"><label>${esc(label)}</label><select name="${esc(key)}"><option value=""></option>${(field.options||[]).map(o=>`<option value="${esc(o)}" ${String(val)===String(o)?'selected':''}>${esc(o)}</option>`).join('')}</select>${help}</div>`;if(field.type==='multiselect'){const set=new Set(Array.isArray(val)?val:val?[val]:[]);return `<div class="field"><label>${esc(label)}</label><div class="dd-checks">${(field.options||[]).map(o=>`<label class="dd-check"><input type="checkbox" name="${esc(key)}" value="${esc(o)}" ${set.has(o)?'checked':''}><span>${esc(o)}</span></label>`).join('')}</div>${help}</div>`}const type=['text','date','tel','email','number','time'].includes(field.type)?field.type:'text';return `<div class="field"><label>${esc(label)}</label><input class="input" type="${type}" name="${esc(key)}" value="${esc(val)}">${help}</div>`}
function collectForm(form,def,base={}){const out={...base};for(const sec of def.sections||[]){for(const field of sec.fields||[]){if(field.type==='multiselect')out[field.key]=[...form.querySelectorAll(`[name="${CSS.escape(field.key)}"]:checked`)].map(x=>x.value);else{const el=form.querySelector(`[name="${CSS.escape(field.key)}"]`);if(!el)continue;out[field.key]=field.type==='number'&&el.value!==''?Number(el.value):el.value}}}return out}
function modalEdit(row){const def=formDef(row.form_slug);if(!def)return;const payload=row.payload||{};const body=`<div class="notice info"><b>Rascunho editável.</b> Salvar rascunho não exige completar tudo. Ao escolher “Concluir”, o sistema verifica os campos essenciais e mantém como rascunho se ainda faltar informação.</div>${(def.sections||[]).map(sec=>`<div class="dd-section"><h4>${esc(sec.title||'Dados')}</h4><div class="dd-grid">${(sec.fields||[]).map(f=>inputField(f,payload[f.key])).join('')}</div></div>`).join('')}`;document.querySelector('#dd-modal')?.remove();const bg=document.createElement('div');bg.id='dd-modal';bg.className='dd-modal-bg';bg.innerHTML=`<div class="dd-modal"><header><div><h3 style="margin:0">${esc(titleOf(row))}</h3><div class="dd-meta">${row._youth?esc(row._youth.preferred_name||row._youth.full_name):'Documento operacional'}</div></div><button class="btn ghost" type="button" data-close>✕</button></header><form><div class="body">${body}</div><footer><button class="btn secondary" type="button" data-close>Cancelar</button><button class="btn secondary" type="submit" value="draft">Salvar rascunho</button><button class="btn primary" type="submit" value="complete">Concluir documento</button></footer></form></div>`;document.body.appendChild(bg);bg.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>bg.remove());bg.querySelector('form').onsubmit=async e=>{e.preventDefault();const state=e.submitter?.value==='complete'?'complete':'draft',btn=e.submitter;btn.disabled=true;try{const p=collectForm(e.currentTarget,def,payload);if(row.form_slug==='formulario-inicial'&&row.youth_id){await updateYouth(row.youth_id,p);const saved=await saveFormSubmission('formulario-inicial',row.youth_id,p);const id=saved?.id||row.id;const u=await c().from('methodology_form_submissions').update({record_state:state}).eq('id',id).select('id,record_state,incomplete_fields').single();if(u.error)throw u.error;if(state==='complete'&&u.data.record_state!=='complete')throw new Error('O documento foi salvo como rascunho porque ainda há dados essenciais incompletos: '+(u.data.incomplete_fields||[]).map(missingLabel).join(', '));}else{const u=await c().from('methodology_form_submissions').update({payload:p,record_state:state,updated_at:new Date().toISOString()}).eq('id',row.id).select('id,record_state,incomplete_fields').single();if(u.error)throw u.error;if(state==='complete'&&u.data.record_state!=='complete')throw new Error('O documento foi salvo como rascunho porque ainda há dados essenciais incompletos: '+(u.data.incomplete_fields||[]).map(missingLabel).join(', '));}bg.remove();render()}catch(err){alert(err.message||err);btn.disabled=false}}}
function canEdit(row){return !!formDef(row.form_slug)&&canFillForm(me?.role,row.form_slug)}
function rowHtml(row){const f=formDef(row.form_slug),src=row.source_type?`<span class="dd-source ${row.source_type==='articulation_demand_records'?'public':''}">${esc(row.source_type==='articulation_demand_records'?'Resposta/registro da Articulação':'Registro vinculado')}</span>`:'';return `<div class="dd-row"><div class="dd-row-head"><div><h4 style="margin:0 0 4px">${esc(titleOf(row))}</h4><div class="dd-meta">${row._youth?esc(row._youth.preferred_name||row._youth.full_name)+' · ':''}atualizado ${esc(fmt(row.updated_at||row.submitted_at))}</div></div>${src}</div>${stateHtml(row)}<div class="dd-actions">${canEdit(row)?`<button class="btn primary" data-dd-edit="${row.id}">Editar / completar</button>`:`<a class="btn secondary" href="${sourceEditLink(row)}">Abrir origem</a>`}<button class="btn secondary" data-dd-export="${row.id}:pdf">PDF</button><button class="btn secondary" data-dd-export="${row.id}:docx">DOCX</button></div></div>`}
async function render(){if(!isRoute()||rendering||!me?.active)return;const h=document.querySelector('.content');if(!h)return;rendering=true;try{const rows=await load(),visible=filterRows(rows),drafts=rows.filter(x=>x.record_state!=='complete'||(x.incomplete_fields||[]).length).length,completed=rows.length-drafts,filter=params().get('filter')||'rascunhos';h.innerHTML=`<div class="dd-head"><div><h2>Documentos e Evidências</h2><p>Rascunhos, anexos metodológicos e evidências institucionais em um só lugar.</p></div></div><div class="notice info"><b>Regra de trabalho:</b> todo registro nasce editável. Documento incompleto permanece como rascunho; concluir não apaga o histórico e PDF/DOCX podem ser gerados a qualquer momento.</div><div class="dd-kpis"><div class="dd-kpi"><b>${drafts}</b><span>rascunhos / incompletos</span></div><div class="dd-kpi"><b>${completed}</b><span>concluídos</span></div><div class="dd-kpi"><b>${rows.length}</b><span>documentos acessíveis</span></div></div><div class="dd-filter">${[['rascunhos','Rascunhos'],['todos','Todos'],['anexos','Anexos 1–13'],['articulacao','Articulação'],['concluidos','Concluídos']].map(([v,l])=>`<button class="${filter===v?'active':''}" data-dd-filter="${v}">${l}</button>`).join('')}</div><div class="dd-card">${visible.map(rowHtml).join('')||'<div class="empty">Nenhum documento neste filtro.</div>'}</div>`;h.querySelectorAll('[data-dd-filter]').forEach(b=>b.onclick=()=>routeFilter(b.dataset.ddFilter));h.querySelectorAll('[data-dd-edit]').forEach(b=>b.onclick=()=>modalEdit(rows.find(x=>x.id===b.dataset.ddEdit)));h.querySelectorAll('[data-dd-export]').forEach(b=>b.onclick=async()=>{const [id,f]=b.dataset.ddExport.split(':');b.disabled=true;const old=b.textContent;b.textContent='Gerando…';try{await exportDoc(id,f)}catch(e){alert(e.message||e)}finally{b.disabled=false;b.textContent=old}})}catch(e){h.innerHTML=`<div class="notice danger"><b>Falha ao carregar Documentos e Evidências.</b><br>${esc(e.message||e)}<div style="margin-top:9px"><button class="btn primary" data-dd-retry>Tentar novamente</button></div></div>`;h.querySelector('[data-dd-retry]')?.addEventListener('click',render)}finally{rendering=false}}
function schedule(){clearTimeout(timer);timer=setTimeout(render,90)}
async function boot(){if(!(await ready())||!me?.active)return;style();window.addEventListener('hashchange',schedule);new MutationObserver(()=>{if(isRoute())schedule()}).observe(document.body,{subtree:true,childList:true});schedule()}
boot();
