import { apiMode, supabaseClient } from './api.js?v=20261004-2';

let me=null, channel=null, booting=false, rendering=false, refreshTimer=null;
const esc=(v='')=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=v=>v?new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(v)):'—';
const typeLabel=t=>({agendamento:'Agendamento',mobilizacao:'Mobilização',levantamento_demanda:'Levantamento de demanda',mensagem:'Mensagem',solicitacao:'Solicitação'}[t]||t||'Conversa');
const typeIcon=t=>({agendamento:'◷',mobilizacao:'⌖',levantamento_demanda:'◉',mensagem:'✉',solicitacao:'↗'}[t]||'✉');
const statusLabel=s=>({aberto:'Aberto',aguardando_resposta:'Aguardando resposta',resolvido:'Resolvido',pending_technical:'Aguardando Equipe Técnica',pending_requester:'Aguardando solicitante',approved:'Confirmado',rejected:'Recusado',cancelled:'Cancelado',solicitado:'Solicitado',em_elaboracao:'Em elaboração',planejado:'Planejado',em_mobilizacao:'Em mobilização',concluido:'Concluído',relatorio_finalizado:'Relatório finalizado'}[s]||String(s||'Aberto').replaceAll('_',' '));
function client(){if(apiMode()!=='live')throw new Error('Banco ainda não conectado.');return supabaseClient()}
function params(){return new URLSearchParams(location.hash.split('?')[1]||'')}
function isRoute(){return location.hash.startsWith('#caixa-equipes')}
function activeStaff(p){return p&&p.active!==false&&p.role!=='pendente'}

function style(){if(document.querySelector('#team-comms-style'))return;const s=document.createElement('style');s.id='team-comms-style';s.textContent=`
.tc-head{display:flex;justify-content:space-between;gap:14px;align-items:flex-start;margin-bottom:14px}.tc-head h2{margin:0}.tc-shell{display:grid;grid-template-columns:minmax(280px,390px) minmax(0,1fr);gap:14px;min-height:620px}.tc-panel{background:#fff;border:1px solid var(--border,#dde7e3);border-radius:16px;overflow:hidden}.tc-filters{display:flex;gap:6px;flex-wrap:wrap;padding:12px;border-bottom:1px solid #e6ece9}.tc-filters button{border:1px solid #dce5e1;background:#fff;border-radius:999px;padding:7px 10px;cursor:pointer}.tc-filters button.active{background:#0b5b4c;color:#fff;border-color:#0b5b4c}.tc-list{max-height:680px;overflow:auto}.tc-thread{display:block;width:100%;text-align:left;border:0;border-bottom:1px solid #edf1ef;background:#fff;padding:13px;cursor:pointer}.tc-thread:hover,.tc-thread.active{background:#f1f8f5}.tc-thread.unread{border-left:4px solid #0b5b4c}.tc-row{display:flex;justify-content:space-between;gap:10px}.tc-subject{font-weight:750}.tc-meta,.tc-preview{font-size:12px;color:#66736f}.tc-preview{white-space:nowrap;overflow:hidden;text-overflow:ellipsis;margin-top:5px}.tc-badge{display:inline-flex;align-items:center;border-radius:999px;background:#eef5f2;padding:4px 7px;font-size:11px}.tc-detail{display:flex;flex-direction:column;min-height:620px}.tc-detail-head{padding:16px;border-bottom:1px solid #e6ece9}.tc-detail-head h3{margin:0 0 5px}.tc-messages{flex:1;padding:16px;overflow:auto;max-height:570px;background:#f7faf9}.tc-msg{max-width:82%;margin:0 0 10px;padding:10px 12px;border-radius:14px;background:#fff;border:1px solid #e1e8e5}.tc-msg.mine{margin-left:auto;background:#e8f6f0;border-color:#cfe6dc}.tc-msg.system{max-width:92%;margin-left:auto;margin-right:auto;background:#fff8e8;border-color:#eed9a8}.tc-msg small{display:block;color:#6c7773;margin-top:5px}.tc-compose{padding:12px;border-top:1px solid #e2e9e6;display:flex;gap:8px}.tc-compose textarea{flex:1;min-height:54px;resize:vertical}.tc-empty{padding:40px 18px;text-align:center;color:#687570}.tc-modal-bg{position:fixed;inset:0;z-index:2147482600;background:rgba(7,18,22,.68);display:grid;place-items:center;padding:16px}.tc-modal{width:min(720px,96vw);background:#fff;border-radius:16px;max-height:92vh;overflow:auto}.tc-modal h3{margin:0}.tc-modal-head,.tc-modal-body,.tc-modal-actions{padding:16px}.tc-modal-head{display:flex;justify-content:space-between;border-bottom:1px solid #e5ebe8}.tc-modal-actions{display:flex;justify-content:flex-end;gap:8px;border-top:1px solid #e5ebe8}.tc-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.tc-dot{width:8px;height:8px;border-radius:50%;background:#0b5b4c;display:inline-block;margin-right:5px}.tc-link{font-size:12px;color:#0b5b4c;text-decoration:none}.tc-statusbar{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:8px}
@media(max-width:850px){.tc-shell{grid-template-columns:1fr}.tc-list{max-height:330px}.tc-detail{min-height:480px}.tc-grid{grid-template-columns:1fr}}
`;document.head.appendChild(s)}

async function waitReady(){for(let i=0;i<80;i++){if(apiMode()==='live'){try{const c=supabaseClient();const {data:{user}}=await c.auth.getUser();if(user)return c}catch{}}await new Promise(r=>setTimeout(r,125))}throw new Error('A sessão não ficou pronta. Recarregue a página.')}
async function resolveProfile(){const c=await waitReady();const {data:{user}}=await c.auth.getUser();if(!user)return null;const {data,error}=await c.from('profiles').select('id,display_name,role,team,active').eq('id',user.id).single();if(error)throw error;return data}

async function loadData(){
  const c=client();
  const [threads,reads,profiles]=await Promise.all([
    c.from('team_threads').select('*').order('last_message_at',{ascending:false}).limit(250),
    c.from('team_thread_reads').select('*').eq('user_id',me.id),
    c.from('profiles').select('id,display_name,role,team,active').eq('active',true).order('display_name')
  ]);
  for(const x of [threads,reads,profiles])if(x.error)throw x.error;
  const ids=(threads.data||[]).map(x=>x.id);
  let messages=[];
  if(ids.length){const q=await c.from('team_thread_messages').select('id,thread_id,sender_user_id,message_type,body,created_at').in('thread_id',ids).order('created_at',{ascending:false}).limit(700);if(q.error)throw q.error;messages=q.data||[]}
  const readMap=new Map((reads.data||[]).map(x=>[x.thread_id,x.last_read_at]));
  const latest=new Map();for(const m of messages)if(!latest.has(m.thread_id))latest.set(m.thread_id,m);
  const profileMap=new Map((profiles.data||[]).map(x=>[x.id,x]));
  const rows=(threads.data||[]).map(t=>{const lm=latest.get(t.id);const lr=readMap.get(t.id);const unread=!!lm&&lm.sender_user_id!==me.id&&(!lr||new Date(lm.created_at)>new Date(lr));return {...t,_latest:lm,_unread:unread}});
  return {threads:rows,messages,profiles:profiles.data||[],profileMap};
}
function unreadCount(d){return d.threads.filter(x=>x._unread).length}
function updateNavBadge(n){document.querySelectorAll('[data-team-inbox-label]').forEach(el=>el.textContent=n?`Caixa das Equipes (${n})`:'Caixa das Equipes')}

function filterName(){return params().get('filter')||'todos'}
function selectedId(){return params().get('thread')||''}
function filtered(rows){const f=filterName();if(f==='nao-lidas')return rows.filter(x=>x._unread);if(f==='agendamentos')return rows.filter(x=>x.thread_type==='agendamento');if(f==='mobilizacao')return rows.filter(x=>x.thread_type==='mobilizacao');if(f==='demandas')return rows.filter(x=>x.thread_type==='levantamento_demanda');if(f==='mensagens')return rows.filter(x=>x.thread_type==='mensagem');return rows}
function setRoute(obj){const p=params();Object.entries(obj).forEach(([k,v])=>v?p.set(k,v):p.delete(k));location.hash='#caixa-equipes'+(p.toString()?'?'+p.toString():'')}
function senderName(m,d){if(!m.sender_user_id)return 'Sistema';return d.profileMap.get(m.sender_user_id)?.display_name||'Colaborador'}
function preview(t){return t._latest?.body||'Processo criado. Aguardando atualizações.'}
function sourceLink(t){if(t.source_type==='articulation_mobilization_request')return '#articulacao?view=solicitacoes';if(t.source_type==='articulation_demand_action')return '#articulacao?view=demandas';if(t.source_type==='appointment_request')return '#agenda';return ''}

function threadList(d){const rows=filtered(d.threads);const current=selectedId();return `<div class="tc-panel"><div class="tc-filters">${[['todos','Todos'],['nao-lidas','Não lidas'],['agendamentos','Agendamentos'],['mobilizacao','Mobilização'],['demandas','Demandas'],['mensagens','Mensagens']].map(([v,l])=>`<button data-tc-filter="${v}" class="${filterName()===v?'active':''}">${l}</button>`).join('')}</div><div class="tc-list">${rows.map(t=>`<button class="tc-thread ${t._unread?'unread':''} ${current===t.id?'active':''}" data-tc-thread="${t.id}"><div class="tc-row"><span class="tc-subject">${t._unread?'<span class="tc-dot"></span>':''}${esc(t.subject)}</span><small>${esc(fmt(t.last_message_at))}</small></div><div class="tc-meta">${typeIcon(t.thread_type)} ${esc(typeLabel(t.thread_type))} · ${esc(statusLabel(t.status))}</div><div class="tc-preview">${esc(preview(t))}</div></button>`).join('')||'<div class="tc-empty">Nenhuma conversa neste filtro.</div>'}</div></div>`}

async function markRead(threadId){const c=client();await c.from('team_thread_reads').upsert({thread_id:threadId,user_id:me.id,last_read_at:new Date().toISOString()},{onConflict:'thread_id,user_id'});await c.from('staff_notifications').update({read_at:new Date().toISOString()}).eq('recipient_user_id',me.id).eq('source_type','team_thread').eq('source_id',threadId).is('read_at',null)}
async function detailHtml(t,d){if(!t)return `<div class="tc-panel tc-detail"><div class="tc-empty"><b>Caixa das Equipes</b><br>Escolha uma conversa ou crie uma nova mensagem.</div></div>`;const c=client();const q=await c.from('team_thread_messages').select('*').eq('thread_id',t.id).order('created_at',{ascending:true});if(q.error)throw q.error;await markRead(t.id);const link=sourceLink(t);return `<div class="tc-panel tc-detail"><div class="tc-detail-head"><div class="tc-row"><div><h3>${esc(t.subject)}</h3><div class="tc-meta">${esc(typeLabel(t.thread_type))} · criada ${esc(fmt(t.created_at))}</div></div><span class="tc-badge">${esc(statusLabel(t.status))}</span></div><div class="tc-statusbar">${link?`<a class="tc-link" href="${link}">Abrir processo relacionado →</a>`:''}<button class="btn ghost" data-tc-toggle-status>${t.status==='resolvido'?'Reabrir conversa':'Marcar como resolvido'}</button></div></div><div class="tc-messages" data-tc-messages>${(q.data||[]).map(m=>`<div class="tc-msg ${m.sender_user_id===me.id?'mine':''} ${m.message_type!=='mensagem'&&m.message_type!=='solicitacao'?'system':''}"><b>${esc(senderName(m,d))}</b><div>${esc(m.body).replace(/\n/g,'<br>')}</div><small>${esc(fmt(m.created_at))} · ${esc(m.message_type==='status'?'atualização do processo':m.message_type==='solicitacao'?'solicitação':'mensagem')}</small></div>`).join('')||'<div class="tc-empty">Ainda não há mensagens registradas.</div>'}</div><form class="tc-compose" data-tc-reply><textarea class="input" name="body" maxlength="4000" placeholder="Escreva uma resposta, combinação ou atualização…" required></textarea><button class="btn primary" type="submit">Enviar</button></form></div>`}

async function render(){if(!isRoute()||rendering||!activeStaff(me))return;const host=document.querySelector('.content');if(!host)return;rendering=true;try{const d=await loadData();updateNavBadge(unreadCount(d));const selected=d.threads.find(x=>x.id===selectedId())||null;host.innerHTML=`<div class="tc-head"><div><h2>Caixa das Equipes</h2><p>Solicitações, respostas, negociações, agendamentos e mensagens internas em um só lugar.</p></div><button class="btn primary" data-tc-new>+ Nova mensagem</button></div><div class="notice info" style="margin-bottom:12px"><b>Histórico do processo:</b> quando uma solicitação é aprovada, recusada, contraproposta, reagendada ou respondida, a atualização aparece automaticamente nesta conversa.</div><div class="tc-shell">${threadList(d)}${await detailHtml(selected,d)}</div>`;bind(host,d,selected);updateNavBadge(unreadCount(await loadData()))}catch(e){host.innerHTML=`<div class="notice danger"><b>Não foi possível carregar a Caixa das Equipes.</b><br>${esc(e.message||e)}<div style="margin-top:10px"><button class="btn primary" data-tc-retry>Tentar novamente</button></div></div>`;host.querySelector('[data-tc-retry]')?.addEventListener('click',()=>schedule(true))}finally{rendering=false}}

function modal(d){document.querySelector('#tc-modal')?.remove();const teams=[...new Set(d.profiles.map(x=>x.team).filter(Boolean))].sort();const bg=document.createElement('div');bg.id='tc-modal';bg.className='tc-modal-bg';bg.innerHTML=`<div class="tc-modal"><div class="tc-modal-head"><h3>Nova mensagem</h3><button class="btn ghost" type="button" data-close>✕</button></div><form><div class="tc-modal-body"><div class="field"><label>Assunto</label><input class="input" name="subject" maxlength="180" required placeholder="Ex.: Combinar apoio para ação de sexta"></div><div class="tc-grid"><div class="field"><label>Enviar para uma equipe</label><select name="team"><option value="">Selecione</option>${teams.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}</select></div><div class="field"><label>Ou para uma pessoa específica</label><select name="user"><option value="">Selecione</option>${d.profiles.filter(x=>x.id!==me.id).map(x=>`<option value="${x.id}">${esc(x.display_name)} · ${esc(x.team||x.role)}</option>`).join('')}</select></div></div><div class="field"><label>Mensagem</label><textarea class="input" name="body" maxlength="4000" required placeholder="Descreva a solicitação, combinação ou informação necessária."></textarea></div></div><div class="tc-modal-actions"><button class="btn secondary" type="button" data-close>Cancelar</button><button class="btn primary" type="submit">Enviar mensagem</button></div></form></div>`;document.body.appendChild(bg);bg.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>bg.remove());bg.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),team=String(f.get('team')||''),user=String(f.get('user')||'');if(!team&&!user){alert('Escolha uma equipe ou uma pessoa.');return}const c=client();const {data:t,error}=await c.from('team_threads').insert({thread_type:'mensagem',subject:String(f.get('subject')||'').trim(),created_by:me.id,target_user_id:user||null,target_team:user?null:team,status:'aberto'}).select('id').single();if(error){alert(error.message);return}const {error:e2}=await c.from('team_thread_messages').insert({thread_id:t.id,sender_user_id:me.id,message_type:'mensagem',body:String(f.get('body')||'').trim()});if(e2){alert(e2.message);return}bg.remove();setRoute({thread:t.id,filter:'todos'})}}

function bind(host,d,selected){host.querySelectorAll('[data-tc-filter]').forEach(b=>b.onclick=()=>setRoute({filter:b.dataset.tcFilter,thread:''}));host.querySelectorAll('[data-tc-thread]').forEach(b=>b.onclick=()=>setRoute({thread:b.dataset.tcThread}));host.querySelector('[data-tc-new]')?.addEventListener('click',()=>modal(d));host.querySelector('[data-tc-reply]')?.addEventListener('submit',async e=>{e.preventDefault();if(!selected)return;const ta=e.currentTarget.querySelector('textarea');const body=ta.value.trim();if(!body)return;const {error}=await client().from('team_thread_messages').insert({thread_id:selected.id,sender_user_id:me.id,message_type:'mensagem',body});if(error){alert(error.message);return}ta.value='';schedule(true)});host.querySelector('[data-tc-toggle-status]')?.addEventListener('click',async()=>{if(!selected)return;const status=selected.status==='resolvido'?'aberto':'resolvido';const {error}=await client().from('team_threads').update({status,updated_at:new Date().toISOString()}).eq('id',selected.id);if(error){alert(error.message);return}await client().from('team_thread_messages').insert({thread_id:selected.id,sender_user_id:me.id,message_type:'status',body:status==='resolvido'?'Conversa marcada como resolvida.':'Conversa reaberta.'});schedule(true)})}

async function refreshBadge(){if(!activeStaff(me))return;try{const d=await loadData();updateNavBadge(unreadCount(d))}catch{}}
function schedule(force=false){clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>{refreshBadge();if(isRoute()&&(force||!rendering))render()},force?40:140)}
function subscribe(){if(channel)return;const c=client();channel=c.channel('crj-team-comms').on('postgres_changes',{event:'*',schema:'public',table:'team_threads'},()=>schedule(true)).on('postgres_changes',{event:'*',schema:'public',table:'team_thread_messages'},()=>schedule(true)).subscribe()}

window.addEventListener('hashchange',()=>setTimeout(()=>schedule(true),30));
(async()=>{if(booting)return;booting=true;try{me=await resolveProfile();if(!activeStaff(me))return;style();subscribe();await refreshBadge();if(isRoute())await render()}catch(e){console.error('Caixa das Equipes:',e);if(isRoute()){const host=document.querySelector('.content');if(host)host.innerHTML=`<div class="notice danger"><b>Falha ao iniciar a Caixa das Equipes.</b><br>${esc(e.message||e)}<div style="margin-top:10px"><button class="btn primary" onclick="location.reload()">Recarregar</button></div></div>`}}finally{booting=false}})();
