import { apiMode, supabaseClient } from './api.js?v=20261004-2';
import { CONFIG } from './config.js';

const TECH_ROLES=new Set(['assistente_social','psicologo','terapeuta_ocupacional','coordenacao_geral','monitoramento']);
const esc=(v='')=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmtDate=v=>v?new Date(String(v).slice(0,10)+'T12:00:00').toLocaleDateString('pt-BR'):'—';
const fmtTime=v=>String(v||'').slice(0,5);
let me=null,activeTab='planning',activePlanId=null,scheduled=false,observer=null;

function onRoute(){return location.hash.startsWith('#equipe-tecnica')}
function month(){const q=location.hash.split('?')[1]||'';return new URLSearchParams(q).get('month')||new Date().toISOString().slice(0,7)}
async function client(){for(let i=0;i<100;i++){if(apiMode()==='live')return supabaseClient();await new Promise(r=>setTimeout(r,60))}throw new Error('Banco ainda não conectado.')}
async function resolveProfile(){const c=await client(),{data:{user}}=await c.auth.getUser();if(!user)return null;const {data}=await c.from('profiles').select('id,role,display_name,active').eq('id',user.id).maybeSingle();return data||null}
function canView(){return me?.active!==false&&TECH_ROLES.has(me?.role)}
function canExecute(){return ['assistente_social','psicologo','terapeuta_ocupacional'].includes(me?.role)}
function toast(text,type='success'){let box=document.querySelector('#tw-toast');if(!box){box=document.createElement('div');box.id='tw-toast';document.body.appendChild(box)}box.className=`tw-toast ${type}`;box.textContent=text;box.hidden=false;clearTimeout(box._t);box._t=setTimeout(()=>box.hidden=true,3600)}

function styles(){if(document.querySelector('#technical-workspace-tabs-css'))return;const s=document.createElement('style');s.id='technical-workspace-tabs-css';s.textContent=`
#technical-workspace-nav{margin:0 0 14px;padding:14px;border:1px solid #dbe6e2;border-radius:16px;background:#fff}.tw-tabs{display:flex;gap:7px;flex-wrap:wrap}.tw-tab{border:1px solid #cfddd8;background:#f7faf9;border-radius:999px;padding:8px 13px;cursor:pointer;font-weight:700}.tw-tab.active{background:#0b5b4c;color:#fff;border-color:#0b5b4c}.tw-panel{margin-top:13px}.tw-panel[hidden]{display:none!important}.tw-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:10px}.tw-card{border:1px solid #dbe6e2;border-radius:13px;padding:12px;background:#fff}.tw-card h4{margin:0 0 5px}.tw-meta{font-size:12px;color:#63736d;display:flex;gap:7px;flex-wrap:wrap;margin:6px 0}.tw-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:9px}.tw-live-preview{margin-top:12px;border:1px solid #cddbd6;border-radius:12px;background:#fbfdfc;padding:12px}.tw-preview-page{background:#fff;border:1px solid #dfe7e4;border-radius:8px;padding:14px;box-shadow:0 2px 9px rgba(0,0,0,.04)}.tw-preview-page h4{margin:0 0 10px;text-align:center}.tw-preview-row{border:1px solid #dfe5e2;border-bottom:0;padding:7px;font-size:12px}.tw-preview-row:last-child{border-bottom:1px solid #dfe5e2}.tw-link-box{margin:12px 0;padding:12px;border:1px solid #b8d8ce;border-radius:12px;background:#f1fbf7}.tw-link-line{display:flex;gap:7px;align-items:center;flex-wrap:wrap}.tw-link-line input{flex:1;min-width:260px}.tw-hidden-old-presence{display:none!important}.tw-evidence-table{width:100%;border-collapse:collapse;font-size:12px}.tw-evidence-table th,.tw-evidence-table td{border:1px solid #dfe5e2;padding:6px;text-align:left}.tw-modal-bg{position:fixed;inset:0;background:rgba(15,25,22,.55);z-index:9998;display:grid;place-items:center;padding:20px}.tw-modal{width:min(1050px,96vw);max-height:92vh;overflow:auto;background:#fff;border-radius:16px}.tw-modal-head{display:flex;justify-content:space-between;align-items:center;padding:14px;border-bottom:1px solid #e1e8e5}.tw-modal-body{padding:14px}.tw-toast{position:fixed;right:18px;bottom:18px;z-index:10000;background:#153d35;color:#fff;padding:10px 14px;border-radius:10px;box-shadow:0 8px 22px rgba(0,0,0,.2)}.tw-toast.danger{background:#8f2626}.tw-doc-list{margin-top:12px}.tw-note{font-size:12px;color:#687771}.tw-loading{padding:16px;text-align:center;color:#687771}
body[data-tw-tab="report"] #technical-program-actions,body[data-tw-tab="evidence"] #technical-program-actions{display:none!important}
`;
document.head.appendChild(s)}

async function loadData(){
  const c=await client(),m=month(),start=m+'-01',d=new Date(start+'T00:00:00Z'),end=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,1)).toISOString().slice(0,10);
  const [pq,eq,sq]=await Promise.all([
    c.from('technical_action_plans').select('id,title,action_type,action_scope,objective,planned_activities,expected_results,planned_date,start_time,end_time,location_type,location_details,status,created_at,updated_at').gte('plan_month',start).lt('plan_month',end).order('planned_date',{ascending:true}),
    c.from('technical_action_executions').select('*').gte('execution_date',start).lt('execution_date',end).order('execution_date',{ascending:false}),
    c.from('methodology_form_submissions').select('id,source_id,payload,submitted_at,updated_at').eq('form_slug','lista-presenca-contato').eq('source_type','technical_action').is('deleted_at',null).order('updated_at',{ascending:false})
  ]);
  for(const q of [pq,eq,sq])if(q.error)throw q.error;
  const plans=pq.data||[],ids=new Set(plans.map(x=>x.id));
  return {plans,executions:(eq.data||[]).filter(x=>ids.has(x.plan_id)),submissions:(sq.data||[]).filter(x=>ids.has(x.source_id))};
}

function navHtml(){return `<section id="technical-workspace-nav"><div><h2 style="margin:0 0 4px">Equipe Técnica</h2><div class="tw-note">Planejamento → execução → presença por link → relatório → evidências.</div></div><div class="tw-tabs" style="margin-top:11px"><button class="tw-tab ${activeTab==='planning'?'active':''}" data-tw-tab="planning">Planejamento</button><button class="tw-tab ${activeTab==='report'?'active':''}" data-tw-tab="report">Relatório de execução</button><button class="tw-tab ${activeTab==='evidence'?'active':''}" data-tw-tab="evidence">Evidências</button></div><div class="tw-panel" id="tw-custom-panel" ${activeTab==='planning'?'hidden':''}><div class="tw-loading">Carregando...</div></div><div class="tw-doc-list" id="tw-planning-docs" ${activeTab==='planning'?'':'hidden'}></div></section>`}

async function ensureWorkspace(){
  if(!onRoute())return;const anchor=document.querySelector('#technical-team-enhancement');if(!anchor)return;
  if(!me)me=await resolveProfile();if(!canView())return;styles();
  let nav=document.querySelector('#technical-workspace-nav');if(!nav){anchor.insertAdjacentHTML('afterbegin',navHtml());nav=document.querySelector('#technical-workspace-nav');bindNav(nav)}
  document.body.dataset.twTab=activeTab;
  await renderTab();
}
function bindNav(nav){nav.querySelectorAll('[data-tw-tab]').forEach(b=>b.addEventListener('click',async()=>{activeTab=b.dataset.twTab;nav.querySelectorAll('[data-tw-tab]').forEach(x=>x.classList.toggle('active',x===b));document.body.dataset.twTab=activeTab;nav.querySelector('#tw-custom-panel').hidden=activeTab==='planning';nav.querySelector('#tw-planning-docs').hidden=activeTab!=='planning';await renderTab()}))}
async function renderTab(){const nav=document.querySelector('#technical-workspace-nav');if(!nav)return;try{const data=await loadData();if(activeTab==='planning')renderPlanningDocs(nav.querySelector('#tw-planning-docs'),data);else if(activeTab==='report')renderReports(nav.querySelector('#tw-custom-panel'),data);else renderEvidence(nav.querySelector('#tw-custom-panel'),data)}catch(err){const target=activeTab==='planning'?nav.querySelector('#tw-planning-docs'):nav.querySelector('#tw-custom-panel');target.innerHTML=`<div class="notice danger"><b>Não foi possível carregar a área.</b><br>${esc(err.message||String(err))}</div>`}}

function planMeta(p){return `${fmtDate(p.planned_date)}${p.start_time?' · '+fmtTime(p.start_time):''}${p.end_time?'–'+fmtTime(p.end_time):''}`}
function renderPlanningDocs(root,data){if(!root)return;root.innerHTML=`<div class="tw-card"><h3 style="margin-top:0">Documentos de planejamento</h3><div class="tw-note">Ao elaborar ou editar um planejamento, a pré-visualização aparece dentro do formulário. Após salvar, o documento pode ser baixado em PDF ou impresso.</div><div class="tw-grid" style="margin-top:10px">${data.plans.map(p=>`<div class="tw-card"><h4>${esc(p.title)}</h4><div class="tw-meta"><span>${esc(p.action_type?.toUpperCase()||'Ação')}</span><span>${esc(planMeta(p))}</span><span>${esc(p.status||'')}</span></div><div class="tw-actions"><button class="btn secondary" data-tw-tech-pdf="plan:${p.id}">Baixar PDF</button><button class="btn" data-tw-tech-print="plan:${p.id}">Imprimir</button></div></div>`).join('')||'<div class="empty">Nenhum planejamento técnico neste mês.</div>'}</div></div>`;bindTechnicalDocs(root)}
function renderReports(root,data){if(!root)return;root.innerHTML=`<div class="tw-card"><div style="display:flex;justify-content:space-between;gap:10px;align-items:flex-start;flex-wrap:wrap"><div><h3 style="margin:0">Relatórios de execução</h3><div class="tw-note">A presença é registrada pelo link público; o relatório consolida a execução e gera a evidência oficial.</div></div></div><div class="tw-grid" style="margin-top:10px">${data.plans.map(p=>{const ex=data.executions.find(x=>x.plan_id===p.id);return `<div class="tw-card"><h4>${esc(p.title)}</h4><div class="tw-meta"><span>${esc(planMeta(p))}</span><span>${ex?esc(ex.execution_status):'Sem execução registrada'}</span></div>${ex?.execution_description?`<div class="tw-note">${esc(ex.execution_description.slice(0,180))}${ex.execution_description.length>180?'…':''}</div>`:''}<div class="tw-actions">${canExecute()?`<button class="btn primary" data-tw-open-execution="${p.id}">${ex?'Editar relatório':'Elaborar relatório'}</button>`:''}${ex?`<button class="btn secondary" data-tw-tech-pdf="report:${ex.id}">Baixar PDF</button><button class="btn" data-tw-tech-print="report:${ex.id}">Imprimir</button>`:''}</div></div>`}).join('')||'<div class="empty">Nenhum planejamento disponível para relatório.</div>'}</div></div>`;
  root.querySelectorAll('[data-tw-open-execution]').forEach(b=>b.addEventListener('click',()=>openUnderlyingExecution(b.dataset.twOpenExecution)));
  bindTechnicalDocs(root)
}
function renderEvidence(root,data){if(!root)return;root.innerHTML=`<div class="tw-card"><h3 style="margin-top:0">Evidências · listas geradas</h3><div class="tw-note">Todas as listas desta área são exibidas e exportadas com o nome completo do cadastro. Nome preferido/apelido não é usado no documento.</div><div class="tw-grid" style="margin-top:10px">${data.submissions.map(s=>{const p=s.payload||{},rows=Array.isArray(p.participants)?p.participants:[];return `<div class="tw-card"><h4>${esc(p.activity||'Lista de presença e contato')}</h4><div class="tw-meta"><span>${esc(fmtDate(p.date))}</span><span>${rows.length} participante(s)</span></div><div class="tw-actions"><button class="btn secondary" data-tw-evidence-preview="${s.id}">Pré-visualizar</button><button class="btn primary" data-crj-evidence-action="pdf" data-evidence-submission-id="${s.id}">Baixar PDF</button><button class="btn" data-crj-evidence-action="print" data-evidence-submission-id="${s.id}">Imprimir</button></div></div>`}).join('')||'<div class="empty">Nenhuma lista gerada neste mês.</div>'}</div></div>`;
  root.querySelectorAll('[data-tw-evidence-preview]').forEach(b=>b.addEventListener('click',()=>{const s=data.submissions.find(x=>x.id===b.dataset.twEvidencePreview);if(s)showEvidence(s)}))
}

function showModal(title,body){document.querySelector('#tw-modal')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="tw-modal-bg" id="tw-modal"><div class="tw-modal"><div class="tw-modal-head"><h3 style="margin:0">${esc(title)}</h3><button class="btn ghost" type="button" data-tw-close>Fechar</button></div><div class="tw-modal-body">${body}</div></div></div>`);const m=document.querySelector('#tw-modal');m.querySelector('[data-tw-close]').addEventListener('click',()=>m.remove());return m}
function evidenceBody(s){const p=s.payload||{},rows=Array.isArray(p.participants)?p.participants:[];return `<div class="tw-preview-page"><h4>LISTA DE PRESENÇA E CONTATO</h4><div class="tw-preview-row"><b>Atividade:</b> ${esc(p.activity||'')}</div><div class="tw-preview-row"><b>Local:</b> ${esc(p.location||'')}</div><div class="tw-preview-row"><b>Data:</b> ${esc(fmtDate(p.date))}</div><div style="overflow:auto;margin-top:10px"><table class="tw-evidence-table"><thead><tr><th>#</th><th>Nome completo</th><th>Nascimento</th><th>CPF</th><th>Telefone</th><th>E-mail</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.full_name||'Nome completo não disponível')}</td><td>${esc(fmtDate(r.birth_date))}</td><td>${esc(r.cpf||'')}</td><td>${esc(r.phone||'')}</td><td>${esc(r.email||'')}</td></tr>`).join('')||'<tr><td colspan="6">Nenhum participante.</td></tr>'}</tbody></table></div></div><div class="tw-actions"><button class="btn primary" data-crj-evidence-action="pdf" data-evidence-submission-id="${s.id}">Baixar PDF</button><button class="btn" data-crj-evidence-action="print" data-evidence-submission-id="${s.id}">Imprimir</button></div>`}
function showEvidence(s){showModal('Evidência · relação de atendimento',evidenceBody(s))}

async function openUnderlyingExecution(planId){activePlanId=planId;let trigger=document.querySelector(`[data-tpa-execute="${CSS.escape(planId)}"]`);if(!trigger){document.querySelector('#technical-program-actions')?.remove();await new Promise(r=>setTimeout(r,350));trigger=document.querySelector(`[data-tpa-execute="${CSS.escape(planId)}"]`)}if(!trigger){toast('A área de execução ainda não terminou de carregar.','danger');return}trigger.click()}

function injectPlanPreview(form){if(form.dataset.twPreview==='1')return;form.dataset.twPreview='1';const box=document.createElement('div');box.className='tw-live-preview';box.innerHTML='<b>Pré-visualização do planejamento</b><div class="tw-preview-page" data-tw-plan-preview style="margin-top:8px"></div>';form.querySelector('.tpa-modal-actions')?.before(box);const update=()=>{const fd=new FormData(form),date=fd.get('planned_date'),start=fd.get('start_time'),end=fd.get('end_time');box.querySelector('[data-tw-plan-preview]').innerHTML=`<h4>${esc(fd.get('title')||'Planejamento técnico')}</h4><div class="tw-preview-row"><b>Ação:</b> ${esc(String(fd.get('action_type')||'').toUpperCase())}</div><div class="tw-preview-row"><b>Data/horário:</b> ${esc(date?fmtDate(date):'A definir')} ${esc(start||'')}${end?'–'+esc(end):''}</div><div class="tw-preview-row"><b>Objetivo:</b> ${esc(fd.get('objective')||'')}</div><div class="tw-preview-row"><b>Atividades/metodologia:</b> ${esc(fd.get('planned_activities')||'')}</div><div class="tw-preview-row"><b>Resultados esperados:</b> ${esc(fd.get('expected_results')||'')}</div>`};form.addEventListener('input',update);form.addEventListener('change',update);update()}

async function openCheckinLink(planId,box){
  box.innerHTML='<div class="tw-loading">Gerando link de execução...</div>';
  try{const c=await client(),{data,error}=await c.rpc('open_technical_action_checkin',{p_plan_id:planId});if(error)throw error;const url=new URL('technical-checkin.html',location.href);url.search='?token='+encodeURIComponent(data.token);const link=url.href;box.innerHTML=`<b>Lista de presença da execução</b><div class="tw-note">Compartilhe este link com os jovens durante a atividade. O fluxo faz identificação, cadastro provisório quando necessário e assinatura.</div><div class="tw-link-line" style="margin-top:8px"><input class="input" readonly value="${esc(link)}" data-tw-link><button type="button" class="btn secondary" data-tw-copy>Copiar link</button><a class="btn" href="${esc(link)}" target="_blank" rel="noopener">Abrir lista</a><button type="button" class="btn ghost" data-tw-count>Atualizar presenças</button></div><div class="tw-note" data-tw-count-label style="margin-top:7px">Consultando presenças...</div>`;box.querySelector('[data-tw-copy]').addEventListener('click',async()=>{await navigator.clipboard.writeText(link);toast('Link da lista copiado.')});const refresh=async()=>{const {data:s,error:e}=await c.rpc('technical_action_checkin_status',{p_plan_id:planId});box.querySelector('[data-tw-count-label]').textContent=e?'Não foi possível consultar a lista.':`${s?.count||0} presença(s) registrada(s) pelo link.`};box.querySelector('[data-tw-count]').addEventListener('click',refresh);await refresh()}catch(err){box.innerHTML=`<div class="notice danger"><b>Não foi possível gerar o link.</b><br>${esc(err.message||String(err))}</div>`}
}
function injectExecutionEnhancement(form){if(form.dataset.twEnhanced==='1')return;form.dataset.twEnhanced='1';const planId=activePlanId;if(!planId)return;
  const oldSection=[...form.querySelectorAll('.tpa-section')].find(x=>x.querySelector('h4')?.textContent?.trim()==='Lista de presença');if(oldSection){oldSection.querySelectorAll('[name="youth_id"]').forEach(x=>x.checked=false);oldSection.classList.add('tw-hidden-old-presence')}
  const linkBox=document.createElement('div');linkBox.className='tw-link-box';if(oldSection)oldSection.before(linkBox);else form.prepend(linkBox);openCheckinLink(planId,linkBox);
  const preview=document.createElement('div');preview.className='tw-live-preview';preview.innerHTML='<b>Pré-visualização do relatório de execução</b><div class="tw-preview-page" data-tw-report-preview style="margin-top:8px"></div>';form.querySelector('.tpa-modal-actions')?.before(preview);
  const update=()=>{const fd=new FormData(form);preview.querySelector('[data-tw-report-preview]').innerHTML=`<h4>RELATÓRIO DE EXECUÇÃO</h4><div class="tw-preview-row"><b>Data:</b> ${esc(fmtDate(fd.get('execution_date')))}</div><div class="tw-preview-row"><b>Horário:</b> ${esc(fd.get('actual_start')||'')}${fd.get('actual_end')?'–'+esc(fd.get('actual_end')):''}</div><div class="tw-preview-row"><b>Situação:</b> ${esc(fd.get('execution_status')||'')}</div><div class="tw-preview-row"><b>Descrição da execução:</b> ${esc(fd.get('execution_description')||'')}</div><div class="tw-preview-row"><b>Resultados alcançados:</b> ${esc(fd.get('results')||'')}</div><div class="tw-preview-row"><b>Encaminhamentos:</b> ${esc(fd.get('referrals')||'')}</div><div class="tw-preview-row"><b>Observações:</b> ${esc(fd.get('observations')||'')}</div>`};form.addEventListener('input',update);form.addEventListener('change',update);update()
}

async function saveExecutionOverride(form){
  const planId=activePlanId;if(!planId)throw new Error('Planejamento da execução não identificado.');const fd=new FormData(form),payload={plan_id:planId,execution_date:fd.get('execution_date')||'',actual_start:fd.get('actual_start')||'',actual_end:fd.get('actual_end')||'',duration_hours:fd.get('duration_hours')||'',execution_status:fd.get('execution_status')||'realizada',execution_description:String(fd.get('execution_description')||'').trim(),results:String(fd.get('results')||'').trim(),referrals:String(fd.get('referrals')||'').trim(),observations:String(fd.get('observations')||'').trim()};const btn=form.querySelector('[type="submit"]'),label=btn?.textContent;if(btn){btn.disabled=true;btn.textContent='Salvando relatório...'}
  try{const c=await client(),{data,error}=await c.rpc('save_technical_action_execution_v2',{p_execution:payload,p_youth_ids:[]});if(error)throw error;document.querySelector('#tpa-modal')?.remove();document.querySelector('#technical-program-actions')?.remove();toast(`Relatório salvo · ${data?.participants||0} presença(s) integrada(s).`);setTimeout(()=>{renderTab();schedule()},180)}catch(err){if(btn){btn.disabled=false;btn.textContent=label||'Salvar relatório + presença'}toast(err.message||String(err),'danger')}
}

async function technicalPdf(kind,id,print=false){const c=await client(),{data:{session}}=await c.auth.getSession();if(!session)throw new Error('Sessão expirada.');const response=await fetch(`${CONFIG.supabaseUrl}/functions/v1/crj-export-technical`,{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json',apikey:CONFIG.supabasePublishableKey},body:JSON.stringify({kind,id})});if(!response.ok){let m='Falha ao gerar PDF.';try{m=(await response.json()).error||m}catch{}throw new Error(m)}const blob=await response.blob(),url=URL.createObjectURL(blob);if(print){const f=document.createElement('iframe');Object.assign(f.style,{position:'fixed',width:'1px',height:'1px',right:'0',bottom:'0',opacity:'0',border:'0'});document.body.appendChild(f);f.onload=()=>setTimeout(()=>{try{f.contentWindow.focus();f.contentWindow.print()}finally{setTimeout(()=>{f.remove();URL.revokeObjectURL(url)},60000)}},350);f.src=url}else{const a=document.createElement('a');a.href=url;a.download=`${kind==='plan'?'planejamento':'relatorio'}-equipe-tecnica.pdf`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000)}}
function bindTechnicalDocs(root){root.querySelectorAll('[data-tw-tech-pdf],[data-tw-tech-print]').forEach(b=>b.addEventListener('click',async()=>{const raw=b.dataset.twTechPdf||b.dataset.twTechPrint,[kind,id]=raw.split(':');b.disabled=true;const old=b.textContent;b.textContent='Gerando...';try{await technicalPdf(kind,id,Boolean(b.dataset.twTechPrint));}catch(err){toast(err.message||String(err),'danger')}finally{b.disabled=false;b.textContent=old}}))}

async function interceptAttendance(button){const executionId=button.dataset.tpaAttendance;const c=await client(),{data:ex,error}=await c.from('technical_action_executions').select('attendance_submission_id').eq('id',executionId).maybeSingle();if(error||!ex?.attendance_submission_id){toast('Lista de presença não localizada.','danger');return}const {data:s,error:e}=await c.from('methodology_form_submissions').select('id,payload,submitted_at,updated_at').eq('id',ex.attendance_submission_id).maybeSingle();if(e||!s){toast('Evidência não localizada.','danger');return}showEvidence(s)}

document.addEventListener('click',e=>{const exec=e.target.closest?.('[data-tpa-execute]');if(exec)activePlanId=exec.dataset.tpaExecute;const att=e.target.closest?.('[data-tpa-attendance]');if(att){e.preventDefault();e.stopImmediatePropagation();interceptAttendance(att)}},true);
document.addEventListener('submit',e=>{const form=e.target;if(form?.id!=='tpa-exec-form'||!form.dataset.twEnhanced)return;e.preventDefault();e.stopImmediatePropagation();saveExecutionOverride(form)},true);

function enhanceModals(){const plan=document.querySelector('#tpa-plan-form');if(plan)injectPlanPreview(plan);const exec=document.querySelector('#tpa-exec-form');if(exec)injectExecutionEnhancement(exec)}
function schedule(){if(scheduled)return;scheduled=true;setTimeout(()=>{scheduled=false;if(onRoute()){ensureWorkspace().catch(err=>console.warn('Technical workspace',err));enhanceModals()}},90)}
observer=new MutationObserver(()=>{enhanceModals();schedule()});observer.observe(document.body,{childList:true,subtree:true});
window.addEventListener('hashchange',()=>{document.querySelector('#technical-workspace-nav')?.remove();activeTab='planning';activePlanId=null;schedule()});
schedule();
