import { apiMode, supabaseClient, saveFormSubmission } from './api.js?v=20261004-2';

let me=null,timer=null,autosaveTimer=null,saving=false;
const esc=(v='')=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function c(){if(apiMode()!=='live')throw new Error('Banco ainda não conectado.');return supabaseClient()}
function routeInfo(){const p=location.hash.split('?')[0].replace(/^#/,'').split('/');return p[0]==='formulario'?{slug:p[1]||'',youthId:p[2]||null}:null}
async function ready(){for(let i=0;i<80;i++){if(apiMode()==='live'){try{const cl=supabaseClient(),{data:{user}}=await cl.auth.getUser();if(user){me=user;return true}}catch{}}await new Promise(r=>setTimeout(r,120))}return false}
function collect(form){const payload={};const grouped=new Map();for(const el of form.querySelectorAll('input[name],select[name],textarea[name]')){if(el.disabled||['submit','button','reset','file'].includes(el.type))continue;const n=el.name;if(!n)continue;if(el.type==='checkbox'){if(!grouped.has(n))grouped.set(n,[]);if(el.checked)grouped.get(n).push(el.value);continue}if(el.type==='radio'){if(el.checked)payload[n]=el.value;continue}if(el.tagName==='SELECT'&&el.multiple){payload[n]=[...el.selectedOptions].map(o=>o.value);continue}let v=el.value;if(el.type==='number'&&v!=='')v=Number(v);payload[n]=v}for(const [k,v] of grouped)payload[k]=v;return payload}
async function findDraft(slug,youthId){let q=c().from('methodology_form_submissions').select('id').eq('form_slug',slug).eq('created_by',me.id).eq('record_state','draft').order('updated_at',{ascending:false}).limit(1);q=youthId?q.eq('youth_id',youthId):q.is('youth_id',null);const r=await q.maybeSingle();if(r.error)throw r.error;return r.data}
async function saveDraft(form,info,automatic=false){if(saving||form.dataset.finalSubmitting==='1')return;saving=true;const btn=document.querySelector('[data-universal-save-draft]'),old=btn?.textContent;if(btn&&!automatic){btn.disabled=true;btn.textContent='Salvando rascunho…'}try{const payload=collect(form);if(info.slug==='formulario-inicial'&&info.youthId){const row=await saveFormSubmission(info.slug,info.youthId,payload);if(row?.id){const u=await c().from('methodology_form_submissions').update({record_state:'draft'}).eq('id',row.id);if(u.error)throw u.error}}else{const existing=await findDraft(info.slug,info.youthId);if(existing){const u=await c().from('methodology_form_submissions').update({payload,record_state:'draft',updated_at:new Date().toISOString()}).eq('id',existing.id);if(u.error)throw u.error}else{const ins=await c().from('methodology_form_submissions').insert({form_slug:info.slug,youth_id:info.youthId,payload,record_state:'draft'});if(ins.error)throw ins.error}}const box=document.querySelector('[data-universal-draft-status]');if(box)box.innerHTML=`<div class="notice success compact"><b>${automatic?'Rascunho salvo automaticamente.':'Rascunho salvo.'}</b> Você pode sair e continuar depois em Documentos e Evidências.</div>`}catch(e){const box=document.querySelector('[data-universal-draft-status]');if(box)box.innerHTML=`<div class="notice danger compact"><b>Não foi possível salvar o rascunho.</b><br>${esc(e.message||e)}</div>`}finally{saving=false;if(btn&&!automatic){btn.disabled=false;btn.textContent=old||'Salvar rascunho'}}}
function queueAutosave(form,info){if(form.dataset.finalSubmitting==='1')return;const box=document.querySelector('[data-universal-draft-status]');if(box)box.innerHTML='<div class="notice info compact">Alterações detectadas · salvando rascunho automaticamente…</div>';clearTimeout(autosaveTimer);autosaveTimer=setTimeout(()=>saveDraft(form,info,true),1200)}
function install(){const info=routeInfo();if(!info||!info.slug)return;const content=document.querySelector('.content');if(!content)return;const form=[...content.querySelectorAll('form')].find(f=>f.querySelector('[name]'));if(!form)return;if(!content.querySelector('[data-universal-draft-panel]')){const panel=document.createElement('div');panel.dataset.universalDraftPanel='1';panel.className='card';panel.style.marginBottom='12px';panel.innerHTML='<div class="notice info"><b>Rascunho automático de trabalho</b><br>Você não precisa completar o formulário de uma vez. Cada alteração é salva automaticamente; também é possível salvar manualmente antes de sair.</div><div data-universal-draft-status></div><div class="actions" style="margin-top:8px"><button class="btn secondary" type="button" data-universal-save-draft>Salvar rascunho agora</button><a class="btn ghost" href="#documentos-evidencias?filter=rascunhos">Ver meus rascunhos</a></div>';const head=content.querySelector('.page-head');if(head)head.insertAdjacentElement('afterend',panel);else content.prepend(panel);panel.querySelector('[data-universal-save-draft]').onclick=()=>saveDraft(form,info,false)}if(form.dataset.universalAutosave!=='1'){form.dataset.universalAutosave='1';form.addEventListener('input',()=>queueAutosave(form,info));form.addEventListener('change',()=>queueAutosave(form,info));form.addEventListener('submit',()=>{form.dataset.finalSubmitting='1';clearTimeout(autosaveTimer)},true)}}
function schedule(){clearTimeout(timer);timer=setTimeout(install,90)}
async function boot(){if(!(await ready()))return;window.addEventListener('hashchange',()=>{clearTimeout(autosaveTimer);schedule()});new MutationObserver(schedule).observe(document.body,{subtree:true,childList:true});schedule()}
boot();
