import {
  apiMode, supabaseClient, getSession, listTeam, listWorkshops,
  createWorkshop, updateWorkshop, generateWorkshopFixedCalendar,
  listWorkshopCalendar, updateWorkshopCalendarEntry, createWorkshopCalendarEntry
} from './api.js?v=20261004-2';

let catalogCache=null, opening=false;
const WRITERS=new Set(['coordenacao_geral','coordenacao_articulacao','educador','administrativo']);
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const time=v=>String(v||'').slice(0,5);
function client(){if(apiMode()!=='live')throw new Error('Banco ainda não conectado.');return supabaseClient()}
function toast(msg,type='success'){const old=document.querySelector('.wd-toast');old?.remove();const d=document.createElement('div');d.className='wd-toast';d.textContent=msg;d.dataset.type=type;document.body.appendChild(d);setTimeout(()=>d.remove(),3400)}
function style(){if(document.querySelector('#workshop-devices-style'))return;const s=document.createElement('style');s.id='workshop-devices-style';s.textContent=`
.wd-modal-bg{position:fixed;inset:0;z-index:2147482500;background:rgba(7,18,22,.68);display:grid;place-items:center;padding:16px}.wd-modal{width:min(880px,97vw);max-height:94vh;overflow:auto;background:#fff;border-radius:18px;box-shadow:0 24px 70px rgba(0,0,0,.28)}.wd-head,.wd-body,.wd-actions{padding:18px}.wd-head{display:flex;justify-content:space-between;gap:14px;align-items:flex-start;border-bottom:1px solid #e4ebe8}.wd-head h3{margin:0}.wd-actions{display:flex;justify-content:flex-end;gap:9px;border-top:1px solid #e4ebe8;position:sticky;bottom:0;background:#fff}.wd-device-box{border:1px solid #dce7e2;border-radius:15px;padding:14px;background:#f9fcfb}.wd-device-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px;margin-top:10px}.wd-device{display:flex;gap:9px;border:1px solid #dce5e1;border-radius:12px;padding:11px;background:#fff;align-items:flex-start}.wd-device input{margin-top:3px}.wd-device strong{display:block}.wd-device small{display:block;color:#64736e;margin-top:2px}.wd-method{margin-top:12px;display:grid;gap:7px}.wd-method-row{border-left:3px solid #8db9aa;background:#fff;padding:8px 10px;border-radius:8px;font-size:12px}.wd-method-row.count{border-left-color:#0b6b58}.wd-method-row b{display:block;font-size:12px}.wd-other{margin-top:10px}.wd-disabled{opacity:.55;pointer-events:none}.wd-toast{position:fixed;right:20px;bottom:20px;z-index:2147483000;background:#163f36;color:white;padding:12px 15px;border-radius:12px;box-shadow:0 14px 40px rgba(0,0,0,.25);max-width:390px}.wd-toast[data-type="danger"]{background:#8b2735}.wd-tag{display:inline-flex;border:1px solid #cfe2da;background:#eef7f3;color:#245e50;border-radius:999px;padding:3px 7px;font-size:11px;margin:3px 3px 0 0}@media(max-width:700px){.wd-device-grid{grid-template-columns:1fr}.wd-actions{flex-wrap:wrap}.wd-actions .btn{flex:1}}
`;document.head.appendChild(s)}

async function me(){const s=await getSession();return s?.user||null}
async function catalog(){if(catalogCache)return catalogCache;const q=await client().from('methodology_device_catalog').select('code,label,description,requires_other_description,methodology_links,sort_order').eq('active',true).order('sort_order');if(q.error)throw q.error;catalogCache=q.data||[];return catalogCache}
async function links(workshopId){if(!workshopId)return [];const q=await client().from('workshop_methodology_devices').select('device_code,other_description').eq('workshop_id',workshopId);if(q.error)throw q.error;return q.data||[]}
async function syncLinks(workshopId,devices){const q=await client().rpc('sync_workshop_methodology_devices',{p_workshop_id:workshopId,p_devices:devices});if(q.error)throw q.error;return q.data||[]}
function formObject(form){const fd=new FormData(form),out={};for(const [k,v] of fd.entries()){if(k==='methodology_devices')continue;if(out[k]!==undefined)out[k]=Array.isArray(out[k])?[...out[k],v]:[out[k],v];else out[k]=v}return out}
function deviceSelection(form){const type=form.querySelector('[name="workshop_type"]')?.value;if(!['permanente','temporaria'].includes(type))return [];const other=String(form.querySelector('[name="device_other_description"]')?.value||'').trim();return [...form.querySelectorAll('[name="methodology_devices"]:checked')].map(x=>({code:x.value,other_description:x.value==='outro'?other:null}))}
function uniqueMethodology(selected,catalogRows,category){const rows=[];const seen=new Set();const add=(x,device)=>{const key=[x.goal_stage,x.indicator_code,x.relation_mode].join('|');if(seen.has(key))return;seen.add(key);rows.push({...x,device})};
  add({goal_stage:'6.1',indicator_code:'M6.1_OFICINAS_HORAS',relation_mode:'count',counts_toward_indicator:true,rationale:'Horas efetivamente executadas da oficina alimentam a carga horária geral de oficinas/cursos.'},'Oficina');
  if(String(category||'').toLowerCase().includes('profissional')){
    add({goal_stage:'4.6',indicator_code:'M4.6_CURSO_HORAS',relation_mode:'count',counts_toward_indicator:true,rationale:'Horas executadas de oficina profissionalizante.'},'Profissionalizante');
    add({goal_stage:'4.6',indicator_code:'M4.6_CURSO_JOVENS_MES',relation_mode:'count',counts_toward_indicator:true,rationale:'Jovens presentes, deduplicados no período.'},'Profissionalizante');
    add({goal_stage:'6.4',indicator_code:'M6.4_CURSO_HORAS',relation_mode:'count',counts_toward_indicator:true,rationale:'Horas executadas de curso/oficina profissionalizante.'},'Profissionalizante');
  }
  for(const code of selected){const c=catalogRows.find(x=>x.code===code);for(const x of c?.methodology_links||[])add(x,c?.label||code)}
  return rows;
}
function methodologyHtml(form,catalogRows){const type=form.querySelector('[name="workshop_type"]')?.value||'';const selected=[...form.querySelectorAll('[name="methodology_devices"]:checked')].map(x=>x.value);const category=form.querySelector('[name="category"]')?.value||'';const host=form.querySelector('[data-wd-methodology]');if(!host)return;
  if(!['permanente','temporaria'].includes(type)){host.innerHTML='<div class="notice warn"><b>Oficina pontual:</b> o vínculo com dispositivos metodológicos fica desativado. Esta regra é exclusiva das oficinas permanentes e temporárias.</div>';return}
  const rows=uniqueMethodology(selected,catalogRows,category);host.innerHTML=rows.length?`<div class="notice info"><b>Contribuição metodológica prevista</b><br><small>Criar/editar apenas define o vínculo. Os números entram quando houver aula e/ou presença executada.</small></div><div class="wd-method">${rows.map(x=>`<div class="wd-method-row ${x.counts_toward_indicator?'count':''}" title="${esc(x.rationale||'')}"><b>Etapa ${esc(x.goal_stage||'—')} · ${esc(x.indicator_code||'Vínculo metodológico')}</b><span>${x.counts_toward_indicator?'✓ Conta quando executada':'◌ Vínculo / exige evidência própria'} · ${esc(x.device||'')}</span><br><small>${esc(x.rationale||'')}</small></div>`).join('')}</div>`:'<div class="notice">Selecione um dispositivo para visualizar as contribuições metodológicas.</div>';
}
function close(){document.querySelector('#workshop-device-modal')?.remove()}

async function open(workshop=null){
  if(opening)return;opening=true;try{
    const user=await me();if(!WRITERS.has(user?.role))return;
    style();const [team,cat,current]=await Promise.all([listTeam(),catalog(),links(workshop?.id)]);const selected=new Map(current.map(x=>[x.device_code,x]));
    const instructors=team.filter(x=>x.active&&(x.role==='oficineiro'||x.id===workshop?.oficineiro_user_id));
    const educators=team.filter(x=>x.active&&(['educador','coordenacao_geral','coordenacao_articulacao'].includes(x.role)||x.id===workshop?.educator_user_id));
    const wd=[['1','Segunda'],['2','Terça'],['3','Quarta'],['4','Quinta'],['5','Sexta'],['6','Sábado'],['0','Domingo']], days=(workshop?.fixed_weekdays||[]).map(Number);
    const bg=document.createElement('div');bg.id='workshop-device-modal';bg.className='wd-modal-bg';
    bg.innerHTML=`<div class="wd-modal"><div class="wd-head"><div><h3>${workshop?'Editar oficina':'Nova oficina'}</h3><p class="muted" style="margin:4px 0 0">Cadastre a oficina e informe a quais dispositivos metodológicos ela pertence.</p></div><button class="btn ghost" type="button" data-wd-close>✕</button></div><form id="workshop-device-form"><div class="wd-body stack">
      <div class="form-grid"><div class="field"><label>Nome da oficina</label><input class="input" name="name" required value="${esc(workshop?.name||'')}"></div><div class="field"><label>Categoria</label><select name="category">${['Esporte','Cultura','Profissionalizante','Arte','Idioma','Outra'].map(x=>`<option ${workshop?.category===x?'selected':''}>${x}</option>`).join('')}</select></div></div>
      <div class="form-grid"><div class="field"><label>Tipo de oficina</label><select name="workshop_type" required><option value="permanente">Permanente</option><option value="temporaria">Temporária</option><option value="pontual">Pontual</option></select></div><div class="field"><label>Forma de calendário</label><select name="schedule_mode" required><option value="semanal_fixa">Semanal fixa em dias da semana</option><option value="calendario_flexivel">Calendário flexível / datas escolhidas</option></select></div></div>
      <div class="field" data-wd-weekdays><label>Dias fixos da semana</label><div class="check-grid">${wd.map(([v,l])=>`<label class="check"><input type="checkbox" name="fixed_weekdays" value="${v}" ${days.includes(Number(v))?'checked':''}><span>${l}</span></label>`).join('')}</div></div>
      <div class="form-grid"><div class="field"><label>Início do calendário</label><input class="input" type="date" name="planned_start_date" value="${esc(workshop?.planned_start_date||'')}"></div><div class="field"><label>Término previsto</label><input class="input" type="date" name="planned_end_date" value="${esc(workshop?.planned_end_date||'')}"><small>Obrigatório nas oficinas temporárias.</small></div></div>
      <div class="form-grid"><div class="field"><label>Horário padrão · início</label><input class="input" type="time" name="start_time" value="${esc(time(workshop?.start_time))}"></div><div class="field"><label>Horário padrão · fim</label><input class="input" type="time" name="end_time" value="${esc(time(workshop?.end_time))}"></div></div>
      <div class="form-grid"><div class="field"><label>Local de realização</label><select name="location_type"><option value="">Selecione</option>${['LABPoca','Sala de computadores','Sala de dança','Trampo Coletivo','Externa','Outro'].map(x=>`<option ${workshop?.location_type===x?'selected':''}>${x}</option>`).join('')}</select><small>O local físico não classifica automaticamente o dispositivo metodológico.</small></div><div class="field"><label>Local externo / outro</label><input class="input" name="location_other" value="${esc(workshop?.location_other||'')}"></div></div>
      <div class="wd-device-box" data-wd-device-box><div><b>Essa oficina está ligada a qual dispositivo?</b><br><small>Marque uma ou mais opções. O vínculo pode ser alterado depois.</small></div><div class="wd-device-grid">${cat.map(c=>`<label class="wd-device"><input type="checkbox" name="methodology_devices" value="${esc(c.code)}" ${selected.has(c.code)?'checked':''}><span><strong>${esc(c.label)}</strong><small>${esc(c.description||'')}</small></span></label>`).join('')}</div><div class="field wd-other" data-wd-other style="display:${selected.has('outro')?'block':'none'}"><label>Qual outro dispositivo?</label><input class="input" name="device_other_description" value="${esc(selected.get('outro')?.other_description||'')}" placeholder="Descreva o dispositivo"></div><div data-wd-methodology style="margin-top:12px"></div></div>
      <div class="form-grid"><div class="field"><label>Oficineiro(a)</label><select name="oficineiro_user_id"><option value="">Ainda não definido</option>${instructors.map(x=>`<option value="${x.id}" ${x.id===workshop?.oficineiro_user_id?'selected':''}>${esc(x.display_name)}</option>`).join('')}</select></div><div class="field"><label>Educador(a) de referência</label><select name="educator_user_id"><option value="">Ainda não definido</option>${educators.map(x=>`<option value="${x.id}" ${x.id===workshop?.educator_user_id?'selected':''}>${esc(x.display_name)}</option>`).join('')}</select></div></div>
      <div class="field"><label>Observações de planejamento</label><textarea name="planning_notes">${esc(workshop?.planning_notes||'')}</textarea></div><div class="field"><label>Situação</label><select name="active"><option value="true">Ativa</option><option value="false">Inativa</option></select></div>
    </div><div class="wd-actions"><button type="button" class="btn" data-wd-close>Cancelar</button><button class="btn primary" type="submit">${workshop?'Salvar alterações':'Criar oficina'}</button></div></form></div>`;
    document.body.appendChild(bg);const form=bg.querySelector('#workshop-device-form');
    form.querySelector('[name="workshop_type"]').value=workshop?.workshop_type||'permanente';form.querySelector('[name="schedule_mode"]').value=workshop?.schedule_mode||'calendario_flexivel';form.querySelector('[name="active"]').value=workshop?.active===false?'false':'true';
    const syncUi=()=>{const type=form.querySelector('[name="workshop_type"]').value,mode=form.querySelector('[name="schedule_mode"]').value,allowed=['permanente','temporaria'].includes(type);form.querySelector('[data-wd-weekdays]').style.display=mode==='semanal_fixa'?'block':'none';form.querySelector('[name="planned_end_date"]').required=type==='temporaria';form.querySelector('[data-wd-device-box]').classList.toggle('wd-disabled',!allowed);form.querySelectorAll('[name="methodology_devices"]').forEach(x=>x.disabled=!allowed);const other=form.querySelector('[name="methodology_devices"][value="outro"]')?.checked;form.querySelector('[data-wd-other]').style.display=allowed&&other?'block':'none';methodologyHtml(form,cat)};
    form.addEventListener('change',syncUi);form.addEventListener('input',e=>{if(e.target.name==='category')methodologyHtml(form,cat)});syncUi();
    bg.querySelectorAll('[data-wd-close]').forEach(x=>x.addEventListener('click',close));bg.addEventListener('click',e=>{if(e.target===bg)close()});
    form.addEventListener('submit',async e=>{e.preventDefault();const p=formObject(form),weekdays=[...form.querySelectorAll('[name="fixed_weekdays"]:checked')].map(x=>x.value);p.fixed_weekdays=weekdays;
      if(!p.planned_start_date){toast('Informe a data de início do calendário.','danger');return}if(!p.start_time||!p.end_time){toast('Informe o horário padrão de início e fim.','danger');return}if(p.end_time<=p.start_time){toast('O horário final deve ser posterior ao horário inicial.','danger');return}if(!p.location_type){toast('Defina o local de realização da oficina.','danger');return}if(['Externa','Outro'].includes(p.location_type)&&!String(p.location_other||'').trim()){toast('Descreva o local externo ou outro local.','danger');return}if(p.workshop_type==='temporaria'&&!p.planned_end_date){toast('Informe a data prevista de término da oficina temporária.','danger');return}if(p.schedule_mode==='semanal_fixa'&&!weekdays.length){toast('Selecione ao menos um dia fixo da semana.','danger');return}
      const devices=deviceSelection(form);if(devices.some(x=>x.code==='outro'&&!x.other_description)){toast('Descreva qual é o outro dispositivo.','danger');return}if(p.workshop_type==='pontual'){p.planned_end_date=p.planned_start_date;p.schedule_mode='calendario_flexivel';p.fixed_weekdays=[]}
      const saveBtn=form.querySelector('button[type="submit"]');saveBtn.disabled=true;saveBtn.textContent='Salvando...';try{const saved=workshop?await updateWorkshop(workshop.id,p):await createWorkshop(p);await syncLinks(saved.id,devices);if(saved.schedule_mode==='semanal_fixa')await generateWorkshopFixedCalendar(saved);if(saved.workshop_type==='pontual'){const oldEntries=await listWorkshopCalendar(null,null,saved.id);for(const ce of oldEntries.filter(x=>x.status==='planejada'))await updateWorkshopCalendarEntry(ce.id,{status:'cancelada'});await createWorkshopCalendarEntry({workshop_id:saved.id,scheduled_date:saved.planned_start_date,start_time:time(saved.start_time),end_time:time(saved.end_time),location_type:saved.location_type,location_other:saved.location_other,source:'manual',status:'planejada',notes:'Gerado a partir do cadastro da oficina pontual'})}close();sessionStorage.setItem('crj_workshop_device_notice',workshop?'Oficina atualizada com vínculos metodológicos.':'Oficina criada com vínculos metodológicos.');location.hash='#oficinas?view=oficinas&_wd='+Date.now()}catch(err){saveBtn.disabled=false;saveBtn.textContent=workshop?'Salvar alterações':'Criar oficina';toast(err.message||String(err),'danger')}})
  }finally{opening=false}
}

async function decorate(){if(!location.hash.startsWith('#oficinas'))return;try{const c=client();await listWorkshops();const q=await c.from('workshop_methodology_devices').select('workshop_id,device_code,methodology_device_catalog(label)');if(q.error)return;const by=new Map();for(const r of q.data||[]){const a=by.get(r.workshop_id)||[];a.push(r.methodology_device_catalog?.label||r.device_code);by.set(r.workshop_id,a)}for(const btn of document.querySelectorAll('[data-edit-workshop]')){const id=btn.dataset.editWorkshop,row=btn.closest('tr,.card');if(!row||row.querySelector('[data-wd-tags]'))continue;const labels=by.get(id)||[];if(!labels.length)continue;const d=document.createElement('div');d.dataset.wdTags='1';d.style.marginTop='6px';d.innerHTML=labels.map(x=>`<span class="wd-tag">${esc(x)}</span>`).join('');(row.querySelector('.name,strong,h3')||row).appendChild(d)}}catch{}
}

document.addEventListener('click',async e=>{const target=e.target.closest?.('[data-action="new-workshop"],[data-edit-workshop]');if(!target)return;let user=null;try{user=await me()}catch{return}if(!WRITERS.has(user?.role))return;e.preventDefault();e.stopImmediatePropagation();if(target.matches('[data-edit-workshop]')){try{const rows=await listWorkshops(),w=rows.find(x=>x.id===target.dataset.editWorkshop);if(w)await open(w)}catch(err){toast(err.message||String(err),'danger')}}else await open(null)},true);
window.addEventListener('hashchange',()=>setTimeout(()=>{style();decorate();const n=sessionStorage.getItem('crj_workshop_device_notice');if(n){sessionStorage.removeItem('crj_workshop_device_notice');toast(n)}},100));
style();setTimeout(decorate,800);
